// Auto-generated by Tools/build_via_keycode_tables.py. Do not edit.
// Source: the-via/app src/utils/key-to-byte/{v10,default}.ts
import Foundation

extension VIAKeycodeMap {
    /// Generated keycode label table for v10.
    static let v10BasicTable: [UInt16: QMKKeycodeLabel] = [
        0x0000: QMKKeycodeLabel(tap: ""),  // KC_NO
        0x0001: QMKKeycodeLabel(tap: ""),  // KC_TRNS
        0x0004: QMKKeycodeLabel(tap: "A"),  // KC_A
        0x0005: QMKKeycodeLabel(tap: "B"),  // KC_B
        0x0006: QMKKeycodeLabel(tap: "C"),  // KC_C
        0x0007: QMKKeycodeLabel(tap: "D"),  // KC_D
        0x0008: QMKKeycodeLabel(tap: "E"),  // KC_E
        0x0009: QMKKeycodeLabel(tap: "F"),  // KC_F
        0x000A: QMKKeycodeLabel(tap: "G"),  // KC_G
        0x000B: QMKKeycodeLabel(tap: "H"),  // KC_H
        0x000C: QMKKeycodeLabel(tap: "I"),  // KC_I
        0x000D: QMKKeycodeLabel(tap: "J"),  // KC_J
        0x000E: QMKKeycodeLabel(tap: "K"),  // KC_K
        0x000F: QMKKeycodeLabel(tap: "L"),  // KC_L
        0x0010: QMKKeycodeLabel(tap: "M"),  // KC_M
        0x0011: QMKKeycodeLabel(tap: "N"),  // KC_N
        0x0012: QMKKeycodeLabel(tap: "O"),  // KC_O
        0x0013: QMKKeycodeLabel(tap: "P"),  // KC_P
        0x0014: QMKKeycodeLabel(tap: "Q"),  // KC_Q
        0x0015: QMKKeycodeLabel(tap: "R"),  // KC_R
        0x0016: QMKKeycodeLabel(tap: "S"),  // KC_S
        0x0017: QMKKeycodeLabel(tap: "T"),  // KC_T
        0x0018: QMKKeycodeLabel(tap: "U"),  // KC_U
        0x0019: QMKKeycodeLabel(tap: "V"),  // KC_V
        0x001A: QMKKeycodeLabel(tap: "W"),  // KC_W
        0x001B: QMKKeycodeLabel(tap: "X"),  // KC_X
        0x001C: QMKKeycodeLabel(tap: "Y"),  // KC_Y
        0x001D: QMKKeycodeLabel(tap: "Z"),  // KC_Z
        0x001E: QMKKeycodeLabel(tap: "1"),  // KC_1
        0x001F: QMKKeycodeLabel(tap: "2"),  // KC_2
        0x0020: QMKKeycodeLabel(tap: "3"),  // KC_3
        0x0021: QMKKeycodeLabel(tap: "4"),  // KC_4
        0x0022: QMKKeycodeLabel(tap: "5"),  // KC_5
        0x0023: QMKKeycodeLabel(tap: "6"),  // KC_6
        0x0024: QMKKeycodeLabel(tap: "7"),  // KC_7
        0x0025: QMKKeycodeLabel(tap: "8"),  // KC_8
        0x0026: QMKKeycodeLabel(tap: "9"),  // KC_9
        0x0027: QMKKeycodeLabel(tap: "0"),  // KC_0
        0x0028: QMKKeycodeLabel(tap: "Enter"),  // KC_ENT
        0x0029: QMKKeycodeLabel(tap: "Esc"),  // KC_ESC
        0x002A: QMKKeycodeLabel(tap: "Bksp"),  // KC_BSPC
        0x002B: QMKKeycodeLabel(tap: "Tab"),  // KC_TAB
        0x002C: QMKKeycodeLabel(tap: "Space"),  // KC_SPC
        0x002D: QMKKeycodeLabel(tap: "-"),  // KC_MINS
        0x002E: QMKKeycodeLabel(tap: "="),  // KC_EQL
        0x002F: QMKKeycodeLabel(tap: "["),  // KC_LBRC
        0x0030: QMKKeycodeLabel(tap: "]"),  // KC_RBRC
        0x0031: QMKKeycodeLabel(tap: "\\"),  // KC_BSLS
        0x0032: QMKKeycodeLabel(tap: "#"),  // KC_NUHS
        0x0033: QMKKeycodeLabel(tap: ";"),  // KC_SCLN
        0x0034: QMKKeycodeLabel(tap: "'"),  // KC_QUOT
        0x0035: QMKKeycodeLabel(tap: "`"),  // KC_GRV
        0x0036: QMKKeycodeLabel(tap: ","),  // KC_COMM
        0x0037: QMKKeycodeLabel(tap: "."),  // KC_DOT
        0x0038: QMKKeycodeLabel(tap: "/"),  // KC_SLSH
        0x0039: QMKKeycodeLabel(tap: "Caps"),  // KC_CAPS
        0x003A: QMKKeycodeLabel(tap: "F1"),  // KC_F1
        0x003B: QMKKeycodeLabel(tap: "F2"),  // KC_F2
        0x003C: QMKKeycodeLabel(tap: "F3"),  // KC_F3
        0x003D: QMKKeycodeLabel(tap: "F4"),  // KC_F4
        0x003E: QMKKeycodeLabel(tap: "F5"),  // KC_F5
        0x003F: QMKKeycodeLabel(tap: "F6"),  // KC_F6
        0x0040: QMKKeycodeLabel(tap: "F7"),  // KC_F7
        0x0041: QMKKeycodeLabel(tap: "F8"),  // KC_F8
        0x0042: QMKKeycodeLabel(tap: "F9"),  // KC_F9
        0x0043: QMKKeycodeLabel(tap: "F10"),  // KC_F10
        0x0044: QMKKeycodeLabel(tap: "F11"),  // KC_F11
        0x0045: QMKKeycodeLabel(tap: "F12"),  // KC_F12
        0x0046: QMKKeycodeLabel(tap: "PrtSc"),  // KC_PSCR
        0x0047: QMKKeycodeLabel(tap: "Slck"),  // KC_SLCK
        0x0048: QMKKeycodeLabel(tap: "Pause"),  // KC_PAUS
        0x0049: QMKKeycodeLabel(tap: "Ins"),  // KC_INS
        0x004A: QMKKeycodeLabel(tap: "Home"),  // KC_HOME
        0x004B: QMKKeycodeLabel(tap: "PgUp"),  // KC_PGUP
        0x004C: QMKKeycodeLabel(tap: "Del"),  // KC_DEL
        0x004D: QMKKeycodeLabel(tap: "End"),  // KC_END
        0x004E: QMKKeycodeLabel(tap: "PgDn"),  // KC_PGDN
        0x004F: QMKKeycodeLabel(tap: "→"),  // KC_RGHT
        0x0050: QMKKeycodeLabel(tap: "←"),  // KC_LEFT
        0x0051: QMKKeycodeLabel(tap: "↓"),  // KC_DOWN
        0x0052: QMKKeycodeLabel(tap: "↑"),  // KC_UP
        0x0053: QMKKeycodeLabel(tap: "Nlck"),  // KC_NLCK
        0x0054: QMKKeycodeLabel(tap: "KP /"),  // KC_PSLS
        0x0055: QMKKeycodeLabel(tap: "KP *"),  // KC_PAST
        0x0056: QMKKeycodeLabel(tap: "KP -"),  // KC_PMNS
        0x0057: QMKKeycodeLabel(tap: "KP +"),  // KC_PPLS
        0x0058: QMKKeycodeLabel(tap: "KP Ent"),  // KC_PENT
        0x0059: QMKKeycodeLabel(tap: "KP 1"),  // KC_P1
        0x005A: QMKKeycodeLabel(tap: "KP 2"),  // KC_P2
        0x005B: QMKKeycodeLabel(tap: "KP 3"),  // KC_P3
        0x005C: QMKKeycodeLabel(tap: "KP 4"),  // KC_P4
        0x005D: QMKKeycodeLabel(tap: "KP 5"),  // KC_P5
        0x005E: QMKKeycodeLabel(tap: "KP 6"),  // KC_P6
        0x005F: QMKKeycodeLabel(tap: "KP 7"),  // KC_P7
        0x0060: QMKKeycodeLabel(tap: "KP 8"),  // KC_P8
        0x0061: QMKKeycodeLabel(tap: "KP 9"),  // KC_P9
        0x0062: QMKKeycodeLabel(tap: "KP 0"),  // KC_P0
        0x0063: QMKKeycodeLabel(tap: "KP ."),  // KC_PDOT
        0x0064: QMKKeycodeLabel(tap: "Non-US \\"),  // KC_NUBS
        0x0065: QMKKeycodeLabel(tap: "Menu"),  // KC_APP
        0x0066: QMKKeycodeLabel(tap: "Power"),  // KC_POWER
        0x0067: QMKKeycodeLabel(tap: "Peql"),  // KC_PEQL
        0x0068: QMKKeycodeLabel(tap: "F13"),  // KC_F13
        0x0069: QMKKeycodeLabel(tap: "F14"),  // KC_F14
        0x006A: QMKKeycodeLabel(tap: "F15"),  // KC_F15
        0x006B: QMKKeycodeLabel(tap: "F16"),  // KC_F16
        0x006C: QMKKeycodeLabel(tap: "F17"),  // KC_F17
        0x006D: QMKKeycodeLabel(tap: "F18"),  // KC_F18
        0x006E: QMKKeycodeLabel(tap: "F19"),  // KC_F19
        0x006F: QMKKeycodeLabel(tap: "F20"),  // KC_F20
        0x0070: QMKKeycodeLabel(tap: "F21"),  // KC_F21
        0x0071: QMKKeycodeLabel(tap: "F22"),  // KC_F22
        0x0072: QMKKeycodeLabel(tap: "F23"),  // KC_F23
        0x0073: QMKKeycodeLabel(tap: "F24"),  // KC_F24
        0x0074: QMKKeycodeLabel(tap: "Execute"),  // KC_EXECUTE
        0x0075: QMKKeycodeLabel(tap: "Help"),  // KC_HELP
        0x0076: QMKKeycodeLabel(tap: "Menu"),  // KC_MENU
        0x0077: QMKKeycodeLabel(tap: "Select"),  // KC_SELECT
        0x0078: QMKKeycodeLabel(tap: "Stop"),  // KC_STOP
        0x0079: QMKKeycodeLabel(tap: "Again"),  // KC_AGAIN
        0x007A: QMKKeycodeLabel(tap: "Undo"),  // KC_UNDO
        0x007B: QMKKeycodeLabel(tap: "Cut"),  // KC_CUT
        0x007C: QMKKeycodeLabel(tap: "Copy"),  // KC_COPY
        0x007D: QMKKeycodeLabel(tap: "Paste"),  // KC_PASTE
        0x007E: QMKKeycodeLabel(tap: "Find"),  // KC_FIND
        0x0082: QMKKeycodeLabel(tap: "Lcap"),  // KC_LCAP
        0x0083: QMKKeycodeLabel(tap: "Lnum"),  // KC_LNUM
        0x0084: QMKKeycodeLabel(tap: "Lscr"),  // KC_LSCR
        0x0085: QMKKeycodeLabel(tap: "Pcmm"),  // KC_PCMM
        0x0086: QMKKeycodeLabel(tap: "Kp Equal As400"),  // KC_KP_EQUAL_AS400
        0x0087: QMKKeycodeLabel(tap: "Ro"),  // KC_RO
        0x0088: QMKKeycodeLabel(tap: "Kana"),  // KC_KANA
        0x0089: QMKKeycodeLabel(tap: "Jyen"),  // KC_JYEN
        0x008A: QMKKeycodeLabel(tap: "Henk"),  // KC_HENK
        0x008B: QMKKeycodeLabel(tap: "Mhen"),  // KC_MHEN
        0x008C: QMKKeycodeLabel(tap: "Int6"),  // KC_INT6
        0x008D: QMKKeycodeLabel(tap: "Int7"),  // KC_INT7
        0x008E: QMKKeycodeLabel(tap: "Int8"),  // KC_INT8
        0x008F: QMKKeycodeLabel(tap: "Int9"),  // KC_INT9
        0x0090: QMKKeycodeLabel(tap: "Haen"),  // KC_HAEN
        0x0091: QMKKeycodeLabel(tap: "Hanj"),  // KC_HANJ
        0x0092: QMKKeycodeLabel(tap: "Lang3"),  // KC_LANG3
        0x0093: QMKKeycodeLabel(tap: "Lang4"),  // KC_LANG4
        0x0094: QMKKeycodeLabel(tap: "Lang5"),  // KC_LANG5
        0x0095: QMKKeycodeLabel(tap: "Lang6"),  // KC_LANG6
        0x0096: QMKKeycodeLabel(tap: "Lang7"),  // KC_LANG7
        0x0097: QMKKeycodeLabel(tap: "Lang8"),  // KC_LANG8
        0x0098: QMKKeycodeLabel(tap: "Lang9"),  // KC_LANG9
        0x0099: QMKKeycodeLabel(tap: "Eras"),  // KC_ERAS
        0x009A: QMKKeycodeLabel(tap: "Sysreq"),  // KC_SYSREQ
        0x009B: QMKKeycodeLabel(tap: "Cancel"),  // KC_CANCEL
        0x009C: QMKKeycodeLabel(tap: "Clr"),  // KC_CLR
        0x009D: QMKKeycodeLabel(tap: "Prior"),  // KC_PRIOR
        0x00A0: QMKKeycodeLabel(tap: "Out"),  // KC_OUT
        0x00A1: QMKKeycodeLabel(tap: "Oper"),  // KC_OPER
        0x00A2: QMKKeycodeLabel(tap: "Clear Again"),  // KC_CLEAR_AGAIN
        0x00A3: QMKKeycodeLabel(tap: "Crsel"),  // KC_CRSEL
        0x00A4: QMKKeycodeLabel(tap: "Exsel"),  // KC_EXSEL
        0x00A5: QMKKeycodeLabel(tap: "Pwr"),  // KC_PWR
        0x00A6: QMKKeycodeLabel(tap: "Slep"),  // KC_SLEP
        0x00A7: QMKKeycodeLabel(tap: "Wake"),  // KC_WAKE
        0x00A8: QMKKeycodeLabel(tap: "Mute"),  // KC_MUTE
        0x00A9: QMKKeycodeLabel(tap: "Vol+"),  // KC_VOLU
        0x00AA: QMKKeycodeLabel(tap: "Vol-"),  // KC_VOLD
        0x00AB: QMKKeycodeLabel(tap: "Next"),  // KC_MNXT
        0x00AC: QMKKeycodeLabel(tap: "Prev"),  // KC_MPRV
        0x00AD: QMKKeycodeLabel(tap: "Stop"),  // KC_MSTP
        0x00AE: QMKKeycodeLabel(tap: "Play"),  // KC_MPLY
        0x00AF: QMKKeycodeLabel(tap: "Media"),  // KC_MSEL
        0x00B0: QMKKeycodeLabel(tap: "Eject"),  // KC_EJCT
        0x00B1: QMKKeycodeLabel(tap: "Mail"),  // KC_MAIL
        0x00B2: QMKKeycodeLabel(tap: "Calc"),  // KC_CALC
        0x00B3: QMKKeycodeLabel(tap: "PC"),  // KC_MYCM
        0x00B4: QMKKeycodeLabel(tap: "Search"),  // KC_WWW_SEARCH
        0x00B5: QMKKeycodeLabel(tap: "Home"),  // KC_WWW_HOME
        0x00B6: QMKKeycodeLabel(tap: "Back"),  // KC_WWW_BACK
        0x00B7: QMKKeycodeLabel(tap: "Fwd"),  // KC_WWW_FORWARD
        0x00B8: QMKKeycodeLabel(tap: "Stop"),  // KC_WWW_STOP
        0x00B9: QMKKeycodeLabel(tap: "Refresh"),  // KC_WWW_REFRESH
        0x00BA: QMKKeycodeLabel(tap: "Favs"),  // KC_WWW_FAVORITES
        0x00BB: QMKKeycodeLabel(tap: "FF"),  // KC_MFFD
        0x00BC: QMKKeycodeLabel(tap: "Rew"),  // KC_MRWD
        0x00BD: QMKKeycodeLabel(tap: "Bright+"),  // KC_BRIU
        0x00BE: QMKKeycodeLabel(tap: "Bright-"),  // KC_BRID
        0x00E0: QMKKeycodeLabel(tap: "LCtrl"),  // KC_LCTL
        0x00E1: QMKKeycodeLabel(tap: "LShift"),  // KC_LSFT
        0x00E2: QMKKeycodeLabel(tap: "LAlt"),  // KC_LALT
        0x00E3: QMKKeycodeLabel(tap: "LCmd"),  // KC_LGUI
        0x00E4: QMKKeycodeLabel(tap: "RCtrl"),  // KC_RCTL
        0x00E5: QMKKeycodeLabel(tap: "RShift"),  // KC_RSFT
        0x00E6: QMKKeycodeLabel(tap: "RAlt"),  // KC_RALT
        0x00E7: QMKKeycodeLabel(tap: "RCmd"),  // KC_RGUI
        0x00F0: QMKKeycodeLabel(tap: "Ms Up"),  // KC_MS_UP
        0x00F1: QMKKeycodeLabel(tap: "Ms Down"),  // KC_MS_DOWN
        0x00F2: QMKKeycodeLabel(tap: "Ms Left"),  // KC_MS_LEFT
        0x00F3: QMKKeycodeLabel(tap: "Ms Right"),  // KC_MS_RIGHT
        0x00F4: QMKKeycodeLabel(tap: "Ms Btn1"),  // KC_MS_BTN1
        0x00F5: QMKKeycodeLabel(tap: "Ms Btn2"),  // KC_MS_BTN2
        0x00F6: QMKKeycodeLabel(tap: "Ms Btn3"),  // KC_MS_BTN3
        0x00F7: QMKKeycodeLabel(tap: "Ms Btn4"),  // KC_MS_BTN4
        0x00F8: QMKKeycodeLabel(tap: "Ms Btn5"),  // KC_MS_BTN5
        0x00F9: QMKKeycodeLabel(tap: "Ms Wh Up"),  // KC_MS_WH_UP
        0x00FA: QMKKeycodeLabel(tap: "Ms Wh Down"),  // KC_MS_WH_DOWN
        0x00FB: QMKKeycodeLabel(tap: "Ms Wh Left"),  // KC_MS_WH_LEFT
        0x00FC: QMKKeycodeLabel(tap: "Ms Wh Right"),  // KC_MS_WH_RIGHT
        0x00FD: QMKKeycodeLabel(tap: "Ms Accel0"),  // KC_MS_ACCEL0
        0x00FE: QMKKeycodeLabel(tap: "Ms Accel1"),  // KC_MS_ACCEL1
        0x00FF: QMKKeycodeLabel(tap: "Ms Accel2"),  // KC_MS_ACCEL2
        0x5C00: QMKKeycodeLabel(tap: "Reset"),  // RESET
        0x5C01: QMKKeycodeLabel(tap: "Debug"),  // DEBUG
        0x5C14: QMKKeycodeLabel(tap: "NKRO"),  // MAGIC_TOGGLE_NKRO
        0x5C16: QMKKeycodeLabel(tap: "GEsc"),  // KC_GESC
        0x5C1D: QMKKeycodeLabel(tap: "Au On"),  // AU_ON
        0x5C1E: QMKKeycodeLabel(tap: "Au Off"),  // AU_OFF
        0x5C1F: QMKKeycodeLabel(tap: "Au Tog"),  // AU_TOG
        0x5C20: QMKKeycodeLabel(tap: "Clicky Toggle"),  // CLICKY_TOGGLE
        0x5C21: QMKKeycodeLabel(tap: "Clicky Enable"),  // CLICKY_ENABLE
        0x5C22: QMKKeycodeLabel(tap: "Clicky Disable"),  // CLICKY_DISABLE
        0x5C23: QMKKeycodeLabel(tap: "Clicky Up"),  // CLICKY_UP
        0x5C24: QMKKeycodeLabel(tap: "Clicky Down"),  // CLICKY_DOWN
        0x5C25: QMKKeycodeLabel(tap: "Clicky Reset"),  // CLICKY_RESET
        0x5C26: QMKKeycodeLabel(tap: "Music On"),  // MU_ON
        0x5C27: QMKKeycodeLabel(tap: "Music Off"),  // MU_OFF
        0x5C28: QMKKeycodeLabel(tap: "Music"),  // MU_TOG
        0x5C29: QMKKeycodeLabel(tap: "Music Mode"),  // MU_MOD
        0x5CBB: QMKKeycodeLabel(tap: "BL On"),  // BL_ON
        0x5CBC: QMKKeycodeLabel(tap: "BL Off"),  // BL_OFF
        0x5CBD: QMKKeycodeLabel(tap: "BL-"),  // BL_DEC
        0x5CBE: QMKKeycodeLabel(tap: "BL+"),  // BL_INC
        0x5CBF: QMKKeycodeLabel(tap: "BL"),  // BL_TOGG
        0x5CC0: QMKKeycodeLabel(tap: "BL Step"),  // BL_STEP
        0x5CC1: QMKKeycodeLabel(tap: "BL Breathe"),  // BL_BRTG
        0x5CC2: QMKKeycodeLabel(tap: "RGB"),  // RGB_TOG
        0x5CC3: QMKKeycodeLabel(tap: "RGB+"),  // RGB_MOD
        0x5CC4: QMKKeycodeLabel(tap: "RGB-"),  // RGB_RMOD
        0x5CC5: QMKKeycodeLabel(tap: "Hue+"),  // RGB_HUI
        0x5CC6: QMKKeycodeLabel(tap: "Hue-"),  // RGB_HUD
        0x5CC7: QMKKeycodeLabel(tap: "Sat+"),  // RGB_SAI
        0x5CC8: QMKKeycodeLabel(tap: "Sat-"),  // RGB_SAD
        0x5CC9: QMKKeycodeLabel(tap: "Val+"),  // RGB_VAI
        0x5CCA: QMKKeycodeLabel(tap: "Val-"),  // RGB_VAD
        0x5CCB: QMKKeycodeLabel(tap: "Speed+"),  // RGB_SPI
        0x5CCC: QMKKeycodeLabel(tap: "Speed-"),  // RGB_SPD
        0x5CCD: QMKKeycodeLabel(tap: "RGB Plain"),  // RGB_M_P
        0x5CCE: QMKKeycodeLabel(tap: "RGB Breathe"),  // RGB_M_B
        0x5CCF: QMKKeycodeLabel(tap: "RGB Rainbow"),  // RGB_M_R
        0x5CD0: QMKKeycodeLabel(tap: "RGB Swirl"),  // RGB_M_SW
        0x5CD1: QMKKeycodeLabel(tap: "RGB Snake"),  // RGB_M_SN
        0x5CD2: QMKKeycodeLabel(tap: "RGB Knight"),  // RGB_M_K
        0x5CD3: QMKKeycodeLabel(tap: "RGB Xmas"),  // RGB_M_X
        0x5CD4: QMKKeycodeLabel(tap: "RGB Gradient"),  // RGB_M_G
        0x5CD7: QMKKeycodeLabel(tap: "Lspo"),  // KC_LSPO
        0x5CD8: QMKKeycodeLabel(tap: "Rspc"),  // KC_RSPC
        0x5CD9: QMKKeycodeLabel(tap: "Sftent"),  // KC_SFTENT
        0x5CF3: QMKKeycodeLabel(tap: "Lcpo"),  // KC_LCPO
        0x5CF4: QMKKeycodeLabel(tap: "Rcpc"),  // KC_RCPC
        0x5CF5: QMKKeycodeLabel(tap: "Lapo"),  // KC_LAPO
        0x5CF6: QMKKeycodeLabel(tap: "Rapc"),  // KC_RAPC
        0x5F00: QMKKeycodeLabel(tap: "Br Inc"),  // BR_INC
        0x5F01: QMKKeycodeLabel(tap: "Br Dec"),  // BR_DEC
        0x5F02: QMKKeycodeLabel(tap: "Ef Inc"),  // EF_INC
        0x5F03: QMKKeycodeLabel(tap: "Ef Dec"),  // EF_DEC
        0x5F04: QMKKeycodeLabel(tap: "Es Inc"),  // ES_INC
        0x5F05: QMKKeycodeLabel(tap: "Es Dec"),  // ES_DEC
        0x5F06: QMKKeycodeLabel(tap: "H1 Inc"),  // H1_INC
        0x5F07: QMKKeycodeLabel(tap: "H1 Dec"),  // H1_DEC
        0x5F08: QMKKeycodeLabel(tap: "S1 Inc"),  // S1_INC
        0x5F09: QMKKeycodeLabel(tap: "S1 Dec"),  // S1_DEC
        0x5F0A: QMKKeycodeLabel(tap: "H2 Inc"),  // H2_INC
        0x5F0B: QMKKeycodeLabel(tap: "H2 Dec"),  // H2_DEC
        0x5F0C: QMKKeycodeLabel(tap: "S2 Inc"),  // S2_INC
        0x5F0D: QMKKeycodeLabel(tap: "S2 Dec"),  // S2_DEC
        0x5F10: QMKKeycodeLabel(tap: "Fn Mo13"),  // FN_MO13
        0x5F11: QMKKeycodeLabel(tap: "Fn Mo23"),  // FN_MO23
    ]
}

extension VIAKeycodeMap {
    /// Generated keycode label table for v11.
    static let v11BasicTable: [UInt16: QMKKeycodeLabel] = [
        0x0000: QMKKeycodeLabel(tap: ""),  // KC_NO
        0x0001: QMKKeycodeLabel(tap: ""),  // KC_TRNS
        0x0004: QMKKeycodeLabel(tap: "A"),  // KC_A
        0x0005: QMKKeycodeLabel(tap: "B"),  // KC_B
        0x0006: QMKKeycodeLabel(tap: "C"),  // KC_C
        0x0007: QMKKeycodeLabel(tap: "D"),  // KC_D
        0x0008: QMKKeycodeLabel(tap: "E"),  // KC_E
        0x0009: QMKKeycodeLabel(tap: "F"),  // KC_F
        0x000A: QMKKeycodeLabel(tap: "G"),  // KC_G
        0x000B: QMKKeycodeLabel(tap: "H"),  // KC_H
        0x000C: QMKKeycodeLabel(tap: "I"),  // KC_I
        0x000D: QMKKeycodeLabel(tap: "J"),  // KC_J
        0x000E: QMKKeycodeLabel(tap: "K"),  // KC_K
        0x000F: QMKKeycodeLabel(tap: "L"),  // KC_L
        0x0010: QMKKeycodeLabel(tap: "M"),  // KC_M
        0x0011: QMKKeycodeLabel(tap: "N"),  // KC_N
        0x0012: QMKKeycodeLabel(tap: "O"),  // KC_O
        0x0013: QMKKeycodeLabel(tap: "P"),  // KC_P
        0x0014: QMKKeycodeLabel(tap: "Q"),  // KC_Q
        0x0015: QMKKeycodeLabel(tap: "R"),  // KC_R
        0x0016: QMKKeycodeLabel(tap: "S"),  // KC_S
        0x0017: QMKKeycodeLabel(tap: "T"),  // KC_T
        0x0018: QMKKeycodeLabel(tap: "U"),  // KC_U
        0x0019: QMKKeycodeLabel(tap: "V"),  // KC_V
        0x001A: QMKKeycodeLabel(tap: "W"),  // KC_W
        0x001B: QMKKeycodeLabel(tap: "X"),  // KC_X
        0x001C: QMKKeycodeLabel(tap: "Y"),  // KC_Y
        0x001D: QMKKeycodeLabel(tap: "Z"),  // KC_Z
        0x001E: QMKKeycodeLabel(tap: "1"),  // KC_1
        0x001F: QMKKeycodeLabel(tap: "2"),  // KC_2
        0x0020: QMKKeycodeLabel(tap: "3"),  // KC_3
        0x0021: QMKKeycodeLabel(tap: "4"),  // KC_4
        0x0022: QMKKeycodeLabel(tap: "5"),  // KC_5
        0x0023: QMKKeycodeLabel(tap: "6"),  // KC_6
        0x0024: QMKKeycodeLabel(tap: "7"),  // KC_7
        0x0025: QMKKeycodeLabel(tap: "8"),  // KC_8
        0x0026: QMKKeycodeLabel(tap: "9"),  // KC_9
        0x0027: QMKKeycodeLabel(tap: "0"),  // KC_0
        0x0028: QMKKeycodeLabel(tap: "Enter"),  // KC_ENT
        0x0029: QMKKeycodeLabel(tap: "Esc"),  // KC_ESC
        0x002A: QMKKeycodeLabel(tap: "Bksp"),  // KC_BSPC
        0x002B: QMKKeycodeLabel(tap: "Tab"),  // KC_TAB
        0x002C: QMKKeycodeLabel(tap: "Space"),  // KC_SPC
        0x002D: QMKKeycodeLabel(tap: "-"),  // KC_MINS
        0x002E: QMKKeycodeLabel(tap: "="),  // KC_EQL
        0x002F: QMKKeycodeLabel(tap: "["),  // KC_LBRC
        0x0030: QMKKeycodeLabel(tap: "]"),  // KC_RBRC
        0x0031: QMKKeycodeLabel(tap: "\\"),  // KC_BSLS
        0x0032: QMKKeycodeLabel(tap: "#"),  // KC_NUHS
        0x0033: QMKKeycodeLabel(tap: ";"),  // KC_SCLN
        0x0034: QMKKeycodeLabel(tap: "'"),  // KC_QUOT
        0x0035: QMKKeycodeLabel(tap: "`"),  // KC_GRV
        0x0036: QMKKeycodeLabel(tap: ","),  // KC_COMM
        0x0037: QMKKeycodeLabel(tap: "."),  // KC_DOT
        0x0038: QMKKeycodeLabel(tap: "/"),  // KC_SLSH
        0x0039: QMKKeycodeLabel(tap: "Caps"),  // KC_CAPS
        0x003A: QMKKeycodeLabel(tap: "F1"),  // KC_F1
        0x003B: QMKKeycodeLabel(tap: "F2"),  // KC_F2
        0x003C: QMKKeycodeLabel(tap: "F3"),  // KC_F3
        0x003D: QMKKeycodeLabel(tap: "F4"),  // KC_F4
        0x003E: QMKKeycodeLabel(tap: "F5"),  // KC_F5
        0x003F: QMKKeycodeLabel(tap: "F6"),  // KC_F6
        0x0040: QMKKeycodeLabel(tap: "F7"),  // KC_F7
        0x0041: QMKKeycodeLabel(tap: "F8"),  // KC_F8
        0x0042: QMKKeycodeLabel(tap: "F9"),  // KC_F9
        0x0043: QMKKeycodeLabel(tap: "F10"),  // KC_F10
        0x0044: QMKKeycodeLabel(tap: "F11"),  // KC_F11
        0x0045: QMKKeycodeLabel(tap: "F12"),  // KC_F12
        0x0046: QMKKeycodeLabel(tap: "PrtSc"),  // KC_PSCR
        0x0047: QMKKeycodeLabel(tap: "Slck"),  // KC_SLCK
        0x0048: QMKKeycodeLabel(tap: "Pause"),  // KC_PAUS
        0x0049: QMKKeycodeLabel(tap: "Ins"),  // KC_INS
        0x004A: QMKKeycodeLabel(tap: "Home"),  // KC_HOME
        0x004B: QMKKeycodeLabel(tap: "PgUp"),  // KC_PGUP
        0x004C: QMKKeycodeLabel(tap: "Del"),  // KC_DEL
        0x004D: QMKKeycodeLabel(tap: "End"),  // KC_END
        0x004E: QMKKeycodeLabel(tap: "PgDn"),  // KC_PGDN
        0x004F: QMKKeycodeLabel(tap: "→"),  // KC_RGHT
        0x0050: QMKKeycodeLabel(tap: "←"),  // KC_LEFT
        0x0051: QMKKeycodeLabel(tap: "↓"),  // KC_DOWN
        0x0052: QMKKeycodeLabel(tap: "↑"),  // KC_UP
        0x0053: QMKKeycodeLabel(tap: "Nlck"),  // KC_NLCK
        0x0054: QMKKeycodeLabel(tap: "KP /"),  // KC_PSLS
        0x0055: QMKKeycodeLabel(tap: "KP *"),  // KC_PAST
        0x0056: QMKKeycodeLabel(tap: "KP -"),  // KC_PMNS
        0x0057: QMKKeycodeLabel(tap: "KP +"),  // KC_PPLS
        0x0058: QMKKeycodeLabel(tap: "KP Ent"),  // KC_PENT
        0x0059: QMKKeycodeLabel(tap: "KP 1"),  // KC_P1
        0x005A: QMKKeycodeLabel(tap: "KP 2"),  // KC_P2
        0x005B: QMKKeycodeLabel(tap: "KP 3"),  // KC_P3
        0x005C: QMKKeycodeLabel(tap: "KP 4"),  // KC_P4
        0x005D: QMKKeycodeLabel(tap: "KP 5"),  // KC_P5
        0x005E: QMKKeycodeLabel(tap: "KP 6"),  // KC_P6
        0x005F: QMKKeycodeLabel(tap: "KP 7"),  // KC_P7
        0x0060: QMKKeycodeLabel(tap: "KP 8"),  // KC_P8
        0x0061: QMKKeycodeLabel(tap: "KP 9"),  // KC_P9
        0x0062: QMKKeycodeLabel(tap: "KP 0"),  // KC_P0
        0x0063: QMKKeycodeLabel(tap: "KP ."),  // KC_PDOT
        0x0064: QMKKeycodeLabel(tap: "Non-US \\"),  // KC_NUBS
        0x0065: QMKKeycodeLabel(tap: "Menu"),  // KC_APP
        0x0066: QMKKeycodeLabel(tap: "Power"),  // KC_POWER
        0x0067: QMKKeycodeLabel(tap: "Peql"),  // KC_PEQL
        0x0068: QMKKeycodeLabel(tap: "F13"),  // KC_F13
        0x0069: QMKKeycodeLabel(tap: "F14"),  // KC_F14
        0x006A: QMKKeycodeLabel(tap: "F15"),  // KC_F15
        0x006B: QMKKeycodeLabel(tap: "F16"),  // KC_F16
        0x006C: QMKKeycodeLabel(tap: "F17"),  // KC_F17
        0x006D: QMKKeycodeLabel(tap: "F18"),  // KC_F18
        0x006E: QMKKeycodeLabel(tap: "F19"),  // KC_F19
        0x006F: QMKKeycodeLabel(tap: "F20"),  // KC_F20
        0x0070: QMKKeycodeLabel(tap: "F21"),  // KC_F21
        0x0071: QMKKeycodeLabel(tap: "F22"),  // KC_F22
        0x0072: QMKKeycodeLabel(tap: "F23"),  // KC_F23
        0x0073: QMKKeycodeLabel(tap: "F24"),  // KC_F24
        0x0074: QMKKeycodeLabel(tap: "Execute"),  // KC_EXECUTE
        0x0075: QMKKeycodeLabel(tap: "Help"),  // KC_HELP
        0x0076: QMKKeycodeLabel(tap: "Menu"),  // KC_MENU
        0x0077: QMKKeycodeLabel(tap: "Select"),  // KC_SELECT
        0x0078: QMKKeycodeLabel(tap: "Stop"),  // KC_STOP
        0x0079: QMKKeycodeLabel(tap: "Again"),  // KC_AGAIN
        0x007A: QMKKeycodeLabel(tap: "Undo"),  // KC_UNDO
        0x007B: QMKKeycodeLabel(tap: "Cut"),  // KC_CUT
        0x007C: QMKKeycodeLabel(tap: "Copy"),  // KC_COPY
        0x007D: QMKKeycodeLabel(tap: "Paste"),  // KC_PASTE
        0x007E: QMKKeycodeLabel(tap: "Find"),  // KC_FIND
        0x0082: QMKKeycodeLabel(tap: "Lcap"),  // KC_LCAP
        0x0083: QMKKeycodeLabel(tap: "Lnum"),  // KC_LNUM
        0x0084: QMKKeycodeLabel(tap: "Lscr"),  // KC_LSCR
        0x0085: QMKKeycodeLabel(tap: "Pcmm"),  // KC_PCMM
        0x0086: QMKKeycodeLabel(tap: "Kp Equal As400"),  // KC_KP_EQUAL_AS400
        0x0087: QMKKeycodeLabel(tap: "Ro"),  // KC_RO
        0x0088: QMKKeycodeLabel(tap: "Kana"),  // KC_KANA
        0x0089: QMKKeycodeLabel(tap: "Jyen"),  // KC_JYEN
        0x008A: QMKKeycodeLabel(tap: "Henk"),  // KC_HENK
        0x008B: QMKKeycodeLabel(tap: "Mhen"),  // KC_MHEN
        0x008C: QMKKeycodeLabel(tap: "Int6"),  // KC_INT6
        0x008D: QMKKeycodeLabel(tap: "Int7"),  // KC_INT7
        0x008E: QMKKeycodeLabel(tap: "Int8"),  // KC_INT8
        0x008F: QMKKeycodeLabel(tap: "Int9"),  // KC_INT9
        0x0090: QMKKeycodeLabel(tap: "Haen"),  // KC_HAEN
        0x0091: QMKKeycodeLabel(tap: "Hanj"),  // KC_HANJ
        0x0092: QMKKeycodeLabel(tap: "Lang3"),  // KC_LANG3
        0x0093: QMKKeycodeLabel(tap: "Lang4"),  // KC_LANG4
        0x0094: QMKKeycodeLabel(tap: "Lang5"),  // KC_LANG5
        0x0095: QMKKeycodeLabel(tap: "Lang6"),  // KC_LANG6
        0x0096: QMKKeycodeLabel(tap: "Lang7"),  // KC_LANG7
        0x0097: QMKKeycodeLabel(tap: "Lang8"),  // KC_LANG8
        0x0098: QMKKeycodeLabel(tap: "Lang9"),  // KC_LANG9
        0x0099: QMKKeycodeLabel(tap: "Eras"),  // KC_ERAS
        0x009A: QMKKeycodeLabel(tap: "Sysreq"),  // KC_SYSREQ
        0x009B: QMKKeycodeLabel(tap: "Cancel"),  // KC_CANCEL
        0x009C: QMKKeycodeLabel(tap: "Clr"),  // KC_CLR
        0x009D: QMKKeycodeLabel(tap: "Prior"),  // KC_PRIOR
        0x00A0: QMKKeycodeLabel(tap: "Out"),  // KC_OUT
        0x00A1: QMKKeycodeLabel(tap: "Oper"),  // KC_OPER
        0x00A2: QMKKeycodeLabel(tap: "Clear Again"),  // KC_CLEAR_AGAIN
        0x00A3: QMKKeycodeLabel(tap: "Crsel"),  // KC_CRSEL
        0x00A4: QMKKeycodeLabel(tap: "Exsel"),  // KC_EXSEL
        0x00A5: QMKKeycodeLabel(tap: "Pwr"),  // KC_PWR
        0x00A6: QMKKeycodeLabel(tap: "Slep"),  // KC_SLEP
        0x00A7: QMKKeycodeLabel(tap: "Wake"),  // KC_WAKE
        0x00A8: QMKKeycodeLabel(tap: "Mute"),  // KC_MUTE
        0x00A9: QMKKeycodeLabel(tap: "Vol+"),  // KC_VOLU
        0x00AA: QMKKeycodeLabel(tap: "Vol-"),  // KC_VOLD
        0x00AB: QMKKeycodeLabel(tap: "Next"),  // KC_MNXT
        0x00AC: QMKKeycodeLabel(tap: "Prev"),  // KC_MPRV
        0x00AD: QMKKeycodeLabel(tap: "Stop"),  // KC_MSTP
        0x00AE: QMKKeycodeLabel(tap: "Play"),  // KC_MPLY
        0x00AF: QMKKeycodeLabel(tap: "Media"),  // KC_MSEL
        0x00B0: QMKKeycodeLabel(tap: "Eject"),  // KC_EJCT
        0x00B1: QMKKeycodeLabel(tap: "Mail"),  // KC_MAIL
        0x00B2: QMKKeycodeLabel(tap: "Calc"),  // KC_CALC
        0x00B3: QMKKeycodeLabel(tap: "PC"),  // KC_MYCM
        0x00B4: QMKKeycodeLabel(tap: "Search"),  // KC_WWW_SEARCH
        0x00B5: QMKKeycodeLabel(tap: "Home"),  // KC_WWW_HOME
        0x00B6: QMKKeycodeLabel(tap: "Back"),  // KC_WWW_BACK
        0x00B7: QMKKeycodeLabel(tap: "Fwd"),  // KC_WWW_FORWARD
        0x00B8: QMKKeycodeLabel(tap: "Stop"),  // KC_WWW_STOP
        0x00B9: QMKKeycodeLabel(tap: "Refresh"),  // KC_WWW_REFRESH
        0x00BA: QMKKeycodeLabel(tap: "Favs"),  // KC_WWW_FAVORITES
        0x00BB: QMKKeycodeLabel(tap: "FF"),  // KC_MFFD
        0x00BC: QMKKeycodeLabel(tap: "Rew"),  // KC_MRWD
        0x00BD: QMKKeycodeLabel(tap: "Bright+"),  // KC_BRIU
        0x00BE: QMKKeycodeLabel(tap: "Bright-"),  // KC_BRID
        0x00CD: QMKKeycodeLabel(tap: "Ms Up"),  // KC_MS_UP
        0x00CE: QMKKeycodeLabel(tap: "Ms Down"),  // KC_MS_DOWN
        0x00CF: QMKKeycodeLabel(tap: "Ms Left"),  // KC_MS_LEFT
        0x00D0: QMKKeycodeLabel(tap: "Ms Right"),  // KC_MS_RIGHT
        0x00D1: QMKKeycodeLabel(tap: "Ms Btn1"),  // KC_MS_BTN1
        0x00D2: QMKKeycodeLabel(tap: "Ms Btn2"),  // KC_MS_BTN2
        0x00D3: QMKKeycodeLabel(tap: "Ms Btn3"),  // KC_MS_BTN3
        0x00D4: QMKKeycodeLabel(tap: "Ms Btn4"),  // KC_MS_BTN4
        0x00D5: QMKKeycodeLabel(tap: "Ms Btn5"),  // KC_MS_BTN5
        0x00D6: QMKKeycodeLabel(tap: "Ms Btn6"),  // KC_MS_BTN6
        0x00D7: QMKKeycodeLabel(tap: "Ms Btn7"),  // KC_MS_BTN7
        0x00D8: QMKKeycodeLabel(tap: "Ms Btn8"),  // KC_MS_BTN8
        0x00D9: QMKKeycodeLabel(tap: "Ms Wh Up"),  // KC_MS_WH_UP
        0x00DA: QMKKeycodeLabel(tap: "Ms Wh Down"),  // KC_MS_WH_DOWN
        0x00DB: QMKKeycodeLabel(tap: "Ms Wh Left"),  // KC_MS_WH_LEFT
        0x00DC: QMKKeycodeLabel(tap: "Ms Wh Right"),  // KC_MS_WH_RIGHT
        0x00DD: QMKKeycodeLabel(tap: "Ms Accel0"),  // KC_MS_ACCEL0
        0x00DE: QMKKeycodeLabel(tap: "Ms Accel1"),  // KC_MS_ACCEL1
        0x00DF: QMKKeycodeLabel(tap: "Ms Accel2"),  // KC_MS_ACCEL2
        0x00E0: QMKKeycodeLabel(tap: "LCtrl"),  // KC_LCTL
        0x00E1: QMKKeycodeLabel(tap: "LShift"),  // KC_LSFT
        0x00E2: QMKKeycodeLabel(tap: "LAlt"),  // KC_LALT
        0x00E3: QMKKeycodeLabel(tap: "LCmd"),  // KC_LGUI
        0x00E4: QMKKeycodeLabel(tap: "RCtrl"),  // KC_RCTL
        0x00E5: QMKKeycodeLabel(tap: "RShift"),  // KC_RSFT
        0x00E6: QMKKeycodeLabel(tap: "RAlt"),  // KC_RALT
        0x00E7: QMKKeycodeLabel(tap: "RCmd"),  // KC_RGUI
        0x7013: QMKKeycodeLabel(tap: "NKRO"),  // MAGIC_TOGGLE_NKRO
        0x7017: QMKKeycodeLabel(tap: "Swap Lctl Lgui"),  // MAGIC_SWAP_LCTL_LGUI
        0x7018: QMKKeycodeLabel(tap: "Unswap Lctl Lgui"),  // MAGIC_UNSWAP_LCTL_LGUI
        0x7019: QMKKeycodeLabel(tap: "Swap Rctl Rgui"),  // MAGIC_SWAP_RCTL_RGUI
        0x701A: QMKKeycodeLabel(tap: "Unswap Rctl Rgui"),  // MAGIC_UNSWAP_RCTL_RGUI
        0x701B: QMKKeycodeLabel(tap: "Swap Ctl Gui"),  // MAGIC_SWAP_CTL_GUI
        0x701C: QMKKeycodeLabel(tap: "Unswap Ctl Gui"),  // MAGIC_UNSWAP_CTL_GUI
        0x701D: QMKKeycodeLabel(tap: "Toggle Ctl Gui"),  // MAGIC_TOGGLE_CTL_GUI
        0x701E: QMKKeycodeLabel(tap: "Ee Hands Left"),  // MAGIC_EE_HANDS_LEFT
        0x701F: QMKKeycodeLabel(tap: "Ee Hands Right"),  // MAGIC_EE_HANDS_RIGHT
        0x7100: QMKKeycodeLabel(tap: "Mi On"),  // MI_ON
        0x7101: QMKKeycodeLabel(tap: "Mi Off"),  // MI_OFF
        0x7102: QMKKeycodeLabel(tap: "Mi Tog"),  // MI_TOG
        0x7110: QMKKeycodeLabel(tap: "Mi C"),  // MI_C
        0x7112: QMKKeycodeLabel(tap: "Mi D"),  // MI_D
        0x7114: QMKKeycodeLabel(tap: "Mi E"),  // MI_E
        0x7115: QMKKeycodeLabel(tap: "Mi F"),  // MI_F
        0x7117: QMKKeycodeLabel(tap: "Mi G"),  // MI_G
        0x7119: QMKKeycodeLabel(tap: "Mi A"),  // MI_A
        0x711B: QMKKeycodeLabel(tap: "Mi B"),  // MI_B
        0x7120: QMKKeycodeLabel(tap: "Mi C 1"),  // MI_C_1
        0x7122: QMKKeycodeLabel(tap: "Mi D 1"),  // MI_D_1
        0x7124: QMKKeycodeLabel(tap: "Mi E 1"),  // MI_E_1
        0x7125: QMKKeycodeLabel(tap: "Mi F 1"),  // MI_F_1
        0x7127: QMKKeycodeLabel(tap: "Mi G 1"),  // MI_G_1
        0x7129: QMKKeycodeLabel(tap: "Mi A 1"),  // MI_A_1
        0x712B: QMKKeycodeLabel(tap: "Mi B 1"),  // MI_B_1
        0x7130: QMKKeycodeLabel(tap: "Mi C 2"),  // MI_C_2
        0x7132: QMKKeycodeLabel(tap: "Mi D 2"),  // MI_D_2
        0x7134: QMKKeycodeLabel(tap: "Mi E 2"),  // MI_E_2
        0x7135: QMKKeycodeLabel(tap: "Mi F 2"),  // MI_F_2
        0x7137: QMKKeycodeLabel(tap: "Mi G 2"),  // MI_G_2
        0x7139: QMKKeycodeLabel(tap: "Mi A 2"),  // MI_A_2
        0x713B: QMKKeycodeLabel(tap: "Mi B 2"),  // MI_B_2
        0x7140: QMKKeycodeLabel(tap: "Mi C 3"),  // MI_C_3
        0x7142: QMKKeycodeLabel(tap: "Mi D 3"),  // MI_D_3
        0x7144: QMKKeycodeLabel(tap: "Mi E 3"),  // MI_E_3
        0x7145: QMKKeycodeLabel(tap: "Mi F 3"),  // MI_F_3
        0x7147: QMKKeycodeLabel(tap: "Mi G 3"),  // MI_G_3
        0x7149: QMKKeycodeLabel(tap: "Mi A 3"),  // MI_A_3
        0x714B: QMKKeycodeLabel(tap: "Mi B 3"),  // MI_B_3
        0x7150: QMKKeycodeLabel(tap: "Mi C 4"),  // MI_C_4
        0x7152: QMKKeycodeLabel(tap: "Mi D 4"),  // MI_D_4
        0x7154: QMKKeycodeLabel(tap: "Mi E 4"),  // MI_E_4
        0x7155: QMKKeycodeLabel(tap: "Mi F 4"),  // MI_F_4
        0x7157: QMKKeycodeLabel(tap: "Mi G 4"),  // MI_G_4
        0x7159: QMKKeycodeLabel(tap: "Mi A 4"),  // MI_A_4
        0x715B: QMKKeycodeLabel(tap: "Mi B 4"),  // MI_B_4
        0x7160: QMKKeycodeLabel(tap: "Mi C 5"),  // MI_C_5
        0x7162: QMKKeycodeLabel(tap: "Mi D 5"),  // MI_D_5
        0x7164: QMKKeycodeLabel(tap: "Mi E 5"),  // MI_E_5
        0x7165: QMKKeycodeLabel(tap: "Mi F 5"),  // MI_F_5
        0x7167: QMKKeycodeLabel(tap: "Mi G 5"),  // MI_G_5
        0x7169: QMKKeycodeLabel(tap: "Mi A 5"),  // MI_A_5
        0x716B: QMKKeycodeLabel(tap: "Mi B 5"),  // MI_B_5
        0x7170: QMKKeycodeLabel(tap: "Mi Oct N2"),  // MI_OCT_N2
        0x7171: QMKKeycodeLabel(tap: "Mi Oct N1"),  // MI_OCT_N1
        0x7172: QMKKeycodeLabel(tap: "Mi Oct 0"),  // MI_OCT_0
        0x7173: QMKKeycodeLabel(tap: "Mi Oct 1"),  // MI_OCT_1
        0x7174: QMKKeycodeLabel(tap: "Mi Oct 2"),  // MI_OCT_2
        0x7175: QMKKeycodeLabel(tap: "Mi Oct 3"),  // MI_OCT_3
        0x7176: QMKKeycodeLabel(tap: "Mi Oct 4"),  // MI_OCT_4
        0x7177: QMKKeycodeLabel(tap: "Mi Oct 5"),  // MI_OCT_5
        0x7178: QMKKeycodeLabel(tap: "Mi Oct 6"),  // MI_OCT_6
        0x7179: QMKKeycodeLabel(tap: "Mi Oct 7"),  // MI_OCT_7
        0x717A: QMKKeycodeLabel(tap: "Mi Octd"),  // MI_OCTD
        0x717B: QMKKeycodeLabel(tap: "Mi Octu"),  // MI_OCTU
        0x7180: QMKKeycodeLabel(tap: "Mi Trns N6"),  // MI_TRNS_N6
        0x7181: QMKKeycodeLabel(tap: "Mi Trns N5"),  // MI_TRNS_N5
        0x7182: QMKKeycodeLabel(tap: "Mi Trns N4"),  // MI_TRNS_N4
        0x7183: QMKKeycodeLabel(tap: "Mi Trns N3"),  // MI_TRNS_N3
        0x7184: QMKKeycodeLabel(tap: "Mi Trns N2"),  // MI_TRNS_N2
        0x7185: QMKKeycodeLabel(tap: "Mi Trns N1"),  // MI_TRNS_N1
        0x7186: QMKKeycodeLabel(tap: "Mi Trns 0"),  // MI_TRNS_0
        0x7187: QMKKeycodeLabel(tap: "Mi Trns 1"),  // MI_TRNS_1
        0x7188: QMKKeycodeLabel(tap: "Mi Trns 2"),  // MI_TRNS_2
        0x7189: QMKKeycodeLabel(tap: "Mi Trns 3"),  // MI_TRNS_3
        0x718A: QMKKeycodeLabel(tap: "Mi Trns 4"),  // MI_TRNS_4
        0x718B: QMKKeycodeLabel(tap: "Mi Trns 5"),  // MI_TRNS_5
        0x718C: QMKKeycodeLabel(tap: "Mi Trns 6"),  // MI_TRNS_6
        0x718D: QMKKeycodeLabel(tap: "Mi Trnsd"),  // MI_TRNSD
        0x718E: QMKKeycodeLabel(tap: "Mi Trnsu"),  // MI_TRNSU
        0x7190: QMKKeycodeLabel(tap: "Mi Vel 0"),  // MI_VEL_0
        0x7191: QMKKeycodeLabel(tap: "Mi Vel 1"),  // MI_VEL_1
        0x7192: QMKKeycodeLabel(tap: "Mi Vel 2"),  // MI_VEL_2
        0x7193: QMKKeycodeLabel(tap: "Mi Vel 3"),  // MI_VEL_3
        0x7194: QMKKeycodeLabel(tap: "Mi Vel 4"),  // MI_VEL_4
        0x7195: QMKKeycodeLabel(tap: "Mi Vel 5"),  // MI_VEL_5
        0x7196: QMKKeycodeLabel(tap: "Mi Vel 6"),  // MI_VEL_6
        0x7197: QMKKeycodeLabel(tap: "Mi Vel 7"),  // MI_VEL_7
        0x7198: QMKKeycodeLabel(tap: "Mi Vel 8"),  // MI_VEL_8
        0x7199: QMKKeycodeLabel(tap: "Mi Vel 9"),  // MI_VEL_9
        0x719A: QMKKeycodeLabel(tap: "Mi Vel 10"),  // MI_VEL_10
        0x719B: QMKKeycodeLabel(tap: "Mi Veld"),  // MI_VELD
        0x719C: QMKKeycodeLabel(tap: "Mi Velu"),  // MI_VELU
        0x71A0: QMKKeycodeLabel(tap: "Mi Ch1"),  // MI_CH1
        0x71A1: QMKKeycodeLabel(tap: "Mi Ch2"),  // MI_CH2
        0x71A2: QMKKeycodeLabel(tap: "Mi Ch3"),  // MI_CH3
        0x71A3: QMKKeycodeLabel(tap: "Mi Ch4"),  // MI_CH4
        0x71A4: QMKKeycodeLabel(tap: "Mi Ch5"),  // MI_CH5
        0x71A5: QMKKeycodeLabel(tap: "Mi Ch6"),  // MI_CH6
        0x71A6: QMKKeycodeLabel(tap: "Mi Ch7"),  // MI_CH7
        0x71A7: QMKKeycodeLabel(tap: "Mi Ch8"),  // MI_CH8
        0x71A8: QMKKeycodeLabel(tap: "Mi Ch9"),  // MI_CH9
        0x71A9: QMKKeycodeLabel(tap: "Mi Ch10"),  // MI_CH10
        0x71AA: QMKKeycodeLabel(tap: "Mi Ch11"),  // MI_CH11
        0x71AB: QMKKeycodeLabel(tap: "Mi Ch12"),  // MI_CH12
        0x71AC: QMKKeycodeLabel(tap: "Mi Ch13"),  // MI_CH13
        0x71AD: QMKKeycodeLabel(tap: "Mi Ch14"),  // MI_CH14
        0x71AE: QMKKeycodeLabel(tap: "Mi Ch15"),  // MI_CH15
        0x71AF: QMKKeycodeLabel(tap: "Mi Ch16"),  // MI_CH16
        0x71B0: QMKKeycodeLabel(tap: "Mi Chd"),  // MI_CHD
        0x71B1: QMKKeycodeLabel(tap: "Mi Chu"),  // MI_CHU
        0x71C0: QMKKeycodeLabel(tap: "Mi Alloff"),  // MI_ALLOFF
        0x71C1: QMKKeycodeLabel(tap: "Mi Sust"),  // MI_SUST
        0x71C2: QMKKeycodeLabel(tap: "Mi Port"),  // MI_PORT
        0x71C3: QMKKeycodeLabel(tap: "Mi Sost"),  // MI_SOST
        0x71C4: QMKKeycodeLabel(tap: "Mi Soft"),  // MI_SOFT
        0x71C5: QMKKeycodeLabel(tap: "Mi Leg"),  // MI_LEG
        0x71C6: QMKKeycodeLabel(tap: "Mi Mod"),  // MI_MOD
        0x71C7: QMKKeycodeLabel(tap: "Mi Modsd"),  // MI_MODSD
        0x71C8: QMKKeycodeLabel(tap: "Mi Modsu"),  // MI_MODSU
        0x71C9: QMKKeycodeLabel(tap: "Mi Bendd"),  // MI_BENDD
        0x71CA: QMKKeycodeLabel(tap: "Mi Bendu"),  // MI_BENDU
        0x7480: QMKKeycodeLabel(tap: "Au On"),  // AU_ON
        0x7481: QMKKeycodeLabel(tap: "Au Off"),  // AU_OFF
        0x7482: QMKKeycodeLabel(tap: "Au Tog"),  // AU_TOG
        0x748A: QMKKeycodeLabel(tap: "Clicky Toggle"),  // CLICKY_TOGGLE
        0x748B: QMKKeycodeLabel(tap: "Clicky Enable"),  // CLICKY_ENABLE
        0x748C: QMKKeycodeLabel(tap: "Clicky Disable"),  // CLICKY_DISABLE
        0x748D: QMKKeycodeLabel(tap: "Clicky Up"),  // CLICKY_UP
        0x748E: QMKKeycodeLabel(tap: "Clicky Down"),  // CLICKY_DOWN
        0x748F: QMKKeycodeLabel(tap: "Clicky Reset"),  // CLICKY_RESET
        0x7490: QMKKeycodeLabel(tap: "Music On"),  // MU_ON
        0x7491: QMKKeycodeLabel(tap: "Music Off"),  // MU_OFF
        0x7492: QMKKeycodeLabel(tap: "Music"),  // MU_TOG
        0x7493: QMKKeycodeLabel(tap: "Music Mode"),  // MU_MOD
        0x7700: QMKKeycodeLabel(tap: "Fn Mo13"),  // FN_MO13
        0x7701: QMKKeycodeLabel(tap: "Fn Mo23"),  // FN_MO23
        0x7800: QMKKeycodeLabel(tap: "BL On"),  // BL_ON
        0x7801: QMKKeycodeLabel(tap: "BL Off"),  // BL_OFF
        0x7802: QMKKeycodeLabel(tap: "BL"),  // BL_TOGG
        0x7803: QMKKeycodeLabel(tap: "BL-"),  // BL_DEC
        0x7804: QMKKeycodeLabel(tap: "BL+"),  // BL_INC
        0x7805: QMKKeycodeLabel(tap: "BL Step"),  // BL_STEP
        0x7806: QMKKeycodeLabel(tap: "BL Breathe"),  // BL_BRTG
        0x7820: QMKKeycodeLabel(tap: "RGB"),  // RGB_TOG
        0x7821: QMKKeycodeLabel(tap: "RGB+"),  // RGB_MOD
        0x7822: QMKKeycodeLabel(tap: "RGB-"),  // RGB_RMOD
        0x7823: QMKKeycodeLabel(tap: "Hue+"),  // RGB_HUI
        0x7824: QMKKeycodeLabel(tap: "Hue-"),  // RGB_HUD
        0x7825: QMKKeycodeLabel(tap: "Sat+"),  // RGB_SAI
        0x7826: QMKKeycodeLabel(tap: "Sat-"),  // RGB_SAD
        0x7827: QMKKeycodeLabel(tap: "Val+"),  // RGB_VAI
        0x7828: QMKKeycodeLabel(tap: "Val-"),  // RGB_VAD
        0x7829: QMKKeycodeLabel(tap: "Speed+"),  // RGB_SPI
        0x782A: QMKKeycodeLabel(tap: "Speed-"),  // RGB_SPD
        0x782B: QMKKeycodeLabel(tap: "RGB Plain"),  // RGB_M_P
        0x782C: QMKKeycodeLabel(tap: "RGB Breathe"),  // RGB_M_B
        0x782D: QMKKeycodeLabel(tap: "RGB Rainbow"),  // RGB_M_R
        0x782E: QMKKeycodeLabel(tap: "RGB Swirl"),  // RGB_M_SW
        0x782F: QMKKeycodeLabel(tap: "RGB Snake"),  // RGB_M_SN
        0x7830: QMKKeycodeLabel(tap: "RGB Knight"),  // RGB_M_K
        0x7831: QMKKeycodeLabel(tap: "RGB Xmas"),  // RGB_M_X
        0x7832: QMKKeycodeLabel(tap: "RGB Gradient"),  // RGB_M_G
        0x7833: QMKKeycodeLabel(tap: "Mode Rgbtest"),  // RGB_MODE_RGBTEST
        0x7C00: QMKKeycodeLabel(tap: "Reset"),  // RESET
        0x7C02: QMKKeycodeLabel(tap: "Debug"),  // DEBUG
        0x7C03: QMKKeycodeLabel(tap: "Clear Eeprom"),  // QK_CLEAR_EEPROM
        0x7C10: QMKKeycodeLabel(tap: "Asdn"),  // KC_ASDN
        0x7C11: QMKKeycodeLabel(tap: "Asup"),  // KC_ASUP
        0x7C12: QMKKeycodeLabel(tap: "Asrp"),  // KC_ASRP
        0x7C13: QMKKeycodeLabel(tap: "Ason"),  // KC_ASON
        0x7C14: QMKKeycodeLabel(tap: "Asoff"),  // KC_ASOFF
        0x7C15: QMKKeycodeLabel(tap: "Astg"),  // KC_ASTG
        0x7C16: QMKKeycodeLabel(tap: "GEsc"),  // KC_GESC
        0x7C17: QMKKeycodeLabel(tap: "Vlk Tog"),  // VLK_TOG
        0x7C18: QMKKeycodeLabel(tap: "Lcpo"),  // KC_LCPO
        0x7C19: QMKKeycodeLabel(tap: "Rcpc"),  // KC_RCPC
        0x7C1A: QMKKeycodeLabel(tap: "Lspo"),  // KC_LSPO
        0x7C1B: QMKKeycodeLabel(tap: "Rspc"),  // KC_RSPC
        0x7C1C: QMKKeycodeLabel(tap: "Lapo"),  // KC_LAPO
        0x7C1D: QMKKeycodeLabel(tap: "Rapc"),  // KC_RAPC
        0x7C1E: QMKKeycodeLabel(tap: "Sftent"),  // KC_SFTENT
        0x7C20: QMKKeycodeLabel(tap: "Out Auto"),  // OUT_AUTO
        0x7C21: QMKKeycodeLabel(tap: "Out Usb"),  // OUT_USB
        0x7C40: QMKKeycodeLabel(tap: "Hpt On"),  // HPT_ON
        0x7C41: QMKKeycodeLabel(tap: "Hpt Off"),  // HPT_OFF
        0x7C42: QMKKeycodeLabel(tap: "Hpt Tog"),  // HPT_TOG
        0x7C43: QMKKeycodeLabel(tap: "Hpt Rst"),  // HPT_RST
        0x7C44: QMKKeycodeLabel(tap: "Hpt Fbk"),  // HPT_FBK
        0x7C45: QMKKeycodeLabel(tap: "Hpt Buz"),  // HPT_BUZ
        0x7C46: QMKKeycodeLabel(tap: "Hpt Modi"),  // HPT_MODI
        0x7C47: QMKKeycodeLabel(tap: "Hpt Modd"),  // HPT_MODD
        0x7C48: QMKKeycodeLabel(tap: "Hpt Cont"),  // HPT_CONT
        0x7C49: QMKKeycodeLabel(tap: "Hpt Coni"),  // HPT_CONI
        0x7C4A: QMKKeycodeLabel(tap: "Hpt Cond"),  // HPT_COND
        0x7C4B: QMKKeycodeLabel(tap: "Hpt Dwli"),  // HPT_DWLI
        0x7C4C: QMKKeycodeLabel(tap: "Hpt Dwld"),  // HPT_DWLD
        0x7C50: QMKKeycodeLabel(tap: "Cmb On"),  // CMB_ON
        0x7C51: QMKKeycodeLabel(tap: "Cmb Off"),  // CMB_OFF
        0x7C52: QMKKeycodeLabel(tap: "Cmb Tog"),  // CMB_TOG
        0x7C53: QMKKeycodeLabel(tap: "Dyn Rec Start1"),  // DYN_REC_START1
        0x7C54: QMKKeycodeLabel(tap: "Dyn Rec Start2"),  // DYN_REC_START2
        0x7C55: QMKKeycodeLabel(tap: "Dyn Rec Stop"),  // DYN_REC_STOP
        0x7C56: QMKKeycodeLabel(tap: "Dyn Macro Play1"),  // DYN_MACRO_PLAY1
        0x7C57: QMKKeycodeLabel(tap: "Dyn Macro Play2"),  // DYN_MACRO_PLAY2
    ]
}

extension VIAKeycodeMap {
    /// Generated keycode label table for v12.
    static let v12BasicTable: [UInt16: QMKKeycodeLabel] = [
        0x0000: QMKKeycodeLabel(tap: ""),  // KC_NO
        0x0001: QMKKeycodeLabel(tap: ""),  // KC_TRNS
        0x0004: QMKKeycodeLabel(tap: "A"),  // KC_A
        0x0005: QMKKeycodeLabel(tap: "B"),  // KC_B
        0x0006: QMKKeycodeLabel(tap: "C"),  // KC_C
        0x0007: QMKKeycodeLabel(tap: "D"),  // KC_D
        0x0008: QMKKeycodeLabel(tap: "E"),  // KC_E
        0x0009: QMKKeycodeLabel(tap: "F"),  // KC_F
        0x000A: QMKKeycodeLabel(tap: "G"),  // KC_G
        0x000B: QMKKeycodeLabel(tap: "H"),  // KC_H
        0x000C: QMKKeycodeLabel(tap: "I"),  // KC_I
        0x000D: QMKKeycodeLabel(tap: "J"),  // KC_J
        0x000E: QMKKeycodeLabel(tap: "K"),  // KC_K
        0x000F: QMKKeycodeLabel(tap: "L"),  // KC_L
        0x0010: QMKKeycodeLabel(tap: "M"),  // KC_M
        0x0011: QMKKeycodeLabel(tap: "N"),  // KC_N
        0x0012: QMKKeycodeLabel(tap: "O"),  // KC_O
        0x0013: QMKKeycodeLabel(tap: "P"),  // KC_P
        0x0014: QMKKeycodeLabel(tap: "Q"),  // KC_Q
        0x0015: QMKKeycodeLabel(tap: "R"),  // KC_R
        0x0016: QMKKeycodeLabel(tap: "S"),  // KC_S
        0x0017: QMKKeycodeLabel(tap: "T"),  // KC_T
        0x0018: QMKKeycodeLabel(tap: "U"),  // KC_U
        0x0019: QMKKeycodeLabel(tap: "V"),  // KC_V
        0x001A: QMKKeycodeLabel(tap: "W"),  // KC_W
        0x001B: QMKKeycodeLabel(tap: "X"),  // KC_X
        0x001C: QMKKeycodeLabel(tap: "Y"),  // KC_Y
        0x001D: QMKKeycodeLabel(tap: "Z"),  // KC_Z
        0x001E: QMKKeycodeLabel(tap: "1"),  // KC_1
        0x001F: QMKKeycodeLabel(tap: "2"),  // KC_2
        0x0020: QMKKeycodeLabel(tap: "3"),  // KC_3
        0x0021: QMKKeycodeLabel(tap: "4"),  // KC_4
        0x0022: QMKKeycodeLabel(tap: "5"),  // KC_5
        0x0023: QMKKeycodeLabel(tap: "6"),  // KC_6
        0x0024: QMKKeycodeLabel(tap: "7"),  // KC_7
        0x0025: QMKKeycodeLabel(tap: "8"),  // KC_8
        0x0026: QMKKeycodeLabel(tap: "9"),  // KC_9
        0x0027: QMKKeycodeLabel(tap: "0"),  // KC_0
        0x0028: QMKKeycodeLabel(tap: "Enter"),  // KC_ENT
        0x0029: QMKKeycodeLabel(tap: "Esc"),  // KC_ESC
        0x002A: QMKKeycodeLabel(tap: "Bksp"),  // KC_BSPC
        0x002B: QMKKeycodeLabel(tap: "Tab"),  // KC_TAB
        0x002C: QMKKeycodeLabel(tap: "Space"),  // KC_SPC
        0x002D: QMKKeycodeLabel(tap: "-"),  // KC_MINS
        0x002E: QMKKeycodeLabel(tap: "="),  // KC_EQL
        0x002F: QMKKeycodeLabel(tap: "["),  // KC_LBRC
        0x0030: QMKKeycodeLabel(tap: "]"),  // KC_RBRC
        0x0031: QMKKeycodeLabel(tap: "\\"),  // KC_BSLS
        0x0032: QMKKeycodeLabel(tap: "#"),  // KC_NUHS
        0x0033: QMKKeycodeLabel(tap: ";"),  // KC_SCLN
        0x0034: QMKKeycodeLabel(tap: "'"),  // KC_QUOT
        0x0035: QMKKeycodeLabel(tap: "`"),  // KC_GRV
        0x0036: QMKKeycodeLabel(tap: ","),  // KC_COMM
        0x0037: QMKKeycodeLabel(tap: "."),  // KC_DOT
        0x0038: QMKKeycodeLabel(tap: "/"),  // KC_SLSH
        0x0039: QMKKeycodeLabel(tap: "Caps"),  // KC_CAPS
        0x003A: QMKKeycodeLabel(tap: "F1"),  // KC_F1
        0x003B: QMKKeycodeLabel(tap: "F2"),  // KC_F2
        0x003C: QMKKeycodeLabel(tap: "F3"),  // KC_F3
        0x003D: QMKKeycodeLabel(tap: "F4"),  // KC_F4
        0x003E: QMKKeycodeLabel(tap: "F5"),  // KC_F5
        0x003F: QMKKeycodeLabel(tap: "F6"),  // KC_F6
        0x0040: QMKKeycodeLabel(tap: "F7"),  // KC_F7
        0x0041: QMKKeycodeLabel(tap: "F8"),  // KC_F8
        0x0042: QMKKeycodeLabel(tap: "F9"),  // KC_F9
        0x0043: QMKKeycodeLabel(tap: "F10"),  // KC_F10
        0x0044: QMKKeycodeLabel(tap: "F11"),  // KC_F11
        0x0045: QMKKeycodeLabel(tap: "F12"),  // KC_F12
        0x0046: QMKKeycodeLabel(tap: "PrtSc"),  // KC_PSCR
        0x0047: QMKKeycodeLabel(tap: "Slck"),  // KC_SLCK
        0x0048: QMKKeycodeLabel(tap: "Pause"),  // KC_PAUS
        0x0049: QMKKeycodeLabel(tap: "Ins"),  // KC_INS
        0x004A: QMKKeycodeLabel(tap: "Home"),  // KC_HOME
        0x004B: QMKKeycodeLabel(tap: "PgUp"),  // KC_PGUP
        0x004C: QMKKeycodeLabel(tap: "Del"),  // KC_DEL
        0x004D: QMKKeycodeLabel(tap: "End"),  // KC_END
        0x004E: QMKKeycodeLabel(tap: "PgDn"),  // KC_PGDN
        0x004F: QMKKeycodeLabel(tap: "→"),  // KC_RGHT
        0x0050: QMKKeycodeLabel(tap: "←"),  // KC_LEFT
        0x0051: QMKKeycodeLabel(tap: "↓"),  // KC_DOWN
        0x0052: QMKKeycodeLabel(tap: "↑"),  // KC_UP
        0x0053: QMKKeycodeLabel(tap: "Nlck"),  // KC_NLCK
        0x0054: QMKKeycodeLabel(tap: "KP /"),  // KC_PSLS
        0x0055: QMKKeycodeLabel(tap: "KP *"),  // KC_PAST
        0x0056: QMKKeycodeLabel(tap: "KP -"),  // KC_PMNS
        0x0057: QMKKeycodeLabel(tap: "KP +"),  // KC_PPLS
        0x0058: QMKKeycodeLabel(tap: "KP Ent"),  // KC_PENT
        0x0059: QMKKeycodeLabel(tap: "KP 1"),  // KC_P1
        0x005A: QMKKeycodeLabel(tap: "KP 2"),  // KC_P2
        0x005B: QMKKeycodeLabel(tap: "KP 3"),  // KC_P3
        0x005C: QMKKeycodeLabel(tap: "KP 4"),  // KC_P4
        0x005D: QMKKeycodeLabel(tap: "KP 5"),  // KC_P5
        0x005E: QMKKeycodeLabel(tap: "KP 6"),  // KC_P6
        0x005F: QMKKeycodeLabel(tap: "KP 7"),  // KC_P7
        0x0060: QMKKeycodeLabel(tap: "KP 8"),  // KC_P8
        0x0061: QMKKeycodeLabel(tap: "KP 9"),  // KC_P9
        0x0062: QMKKeycodeLabel(tap: "KP 0"),  // KC_P0
        0x0063: QMKKeycodeLabel(tap: "KP ."),  // KC_PDOT
        0x0064: QMKKeycodeLabel(tap: "Non-US \\"),  // KC_NUBS
        0x0065: QMKKeycodeLabel(tap: "Menu"),  // KC_APP
        0x0066: QMKKeycodeLabel(tap: "Power"),  // KC_POWER
        0x0067: QMKKeycodeLabel(tap: "Peql"),  // KC_PEQL
        0x0068: QMKKeycodeLabel(tap: "F13"),  // KC_F13
        0x0069: QMKKeycodeLabel(tap: "F14"),  // KC_F14
        0x006A: QMKKeycodeLabel(tap: "F15"),  // KC_F15
        0x006B: QMKKeycodeLabel(tap: "F16"),  // KC_F16
        0x006C: QMKKeycodeLabel(tap: "F17"),  // KC_F17
        0x006D: QMKKeycodeLabel(tap: "F18"),  // KC_F18
        0x006E: QMKKeycodeLabel(tap: "F19"),  // KC_F19
        0x006F: QMKKeycodeLabel(tap: "F20"),  // KC_F20
        0x0070: QMKKeycodeLabel(tap: "F21"),  // KC_F21
        0x0071: QMKKeycodeLabel(tap: "F22"),  // KC_F22
        0x0072: QMKKeycodeLabel(tap: "F23"),  // KC_F23
        0x0073: QMKKeycodeLabel(tap: "F24"),  // KC_F24
        0x0074: QMKKeycodeLabel(tap: "Execute"),  // KC_EXECUTE
        0x0075: QMKKeycodeLabel(tap: "Help"),  // KC_HELP
        0x0076: QMKKeycodeLabel(tap: "Menu"),  // KC_MENU
        0x0077: QMKKeycodeLabel(tap: "Select"),  // KC_SELECT
        0x0078: QMKKeycodeLabel(tap: "Stop"),  // KC_STOP
        0x0079: QMKKeycodeLabel(tap: "Again"),  // KC_AGAIN
        0x007A: QMKKeycodeLabel(tap: "Undo"),  // KC_UNDO
        0x007B: QMKKeycodeLabel(tap: "Cut"),  // KC_CUT
        0x007C: QMKKeycodeLabel(tap: "Copy"),  // KC_COPY
        0x007D: QMKKeycodeLabel(tap: "Paste"),  // KC_PASTE
        0x007E: QMKKeycodeLabel(tap: "Find"),  // KC_FIND
        0x0082: QMKKeycodeLabel(tap: "Lcap"),  // KC_LCAP
        0x0083: QMKKeycodeLabel(tap: "Lnum"),  // KC_LNUM
        0x0084: QMKKeycodeLabel(tap: "Lscr"),  // KC_LSCR
        0x0085: QMKKeycodeLabel(tap: "Pcmm"),  // KC_PCMM
        0x0086: QMKKeycodeLabel(tap: "Kp Equal As400"),  // KC_KP_EQUAL_AS400
        0x0087: QMKKeycodeLabel(tap: "Ro"),  // KC_RO
        0x0088: QMKKeycodeLabel(tap: "Kana"),  // KC_KANA
        0x0089: QMKKeycodeLabel(tap: "Jyen"),  // KC_JYEN
        0x008A: QMKKeycodeLabel(tap: "Henk"),  // KC_HENK
        0x008B: QMKKeycodeLabel(tap: "Mhen"),  // KC_MHEN
        0x008C: QMKKeycodeLabel(tap: "Int6"),  // KC_INT6
        0x008D: QMKKeycodeLabel(tap: "Int7"),  // KC_INT7
        0x008E: QMKKeycodeLabel(tap: "Int8"),  // KC_INT8
        0x008F: QMKKeycodeLabel(tap: "Int9"),  // KC_INT9
        0x0090: QMKKeycodeLabel(tap: "Haen"),  // KC_HAEN
        0x0091: QMKKeycodeLabel(tap: "Hanj"),  // KC_HANJ
        0x0092: QMKKeycodeLabel(tap: "Lang3"),  // KC_LANG3
        0x0093: QMKKeycodeLabel(tap: "Lang4"),  // KC_LANG4
        0x0094: QMKKeycodeLabel(tap: "Lang5"),  // KC_LANG5
        0x0095: QMKKeycodeLabel(tap: "Lang6"),  // KC_LANG6
        0x0096: QMKKeycodeLabel(tap: "Lang7"),  // KC_LANG7
        0x0097: QMKKeycodeLabel(tap: "Lang8"),  // KC_LANG8
        0x0098: QMKKeycodeLabel(tap: "Lang9"),  // KC_LANG9
        0x0099: QMKKeycodeLabel(tap: "Eras"),  // KC_ERAS
        0x009A: QMKKeycodeLabel(tap: "Sysreq"),  // KC_SYSREQ
        0x009B: QMKKeycodeLabel(tap: "Cancel"),  // KC_CANCEL
        0x009C: QMKKeycodeLabel(tap: "Clr"),  // KC_CLR
        0x009D: QMKKeycodeLabel(tap: "Prior"),  // KC_PRIOR
        0x00A0: QMKKeycodeLabel(tap: "Out"),  // KC_OUT
        0x00A1: QMKKeycodeLabel(tap: "Oper"),  // KC_OPER
        0x00A2: QMKKeycodeLabel(tap: "Clear Again"),  // KC_CLEAR_AGAIN
        0x00A3: QMKKeycodeLabel(tap: "Crsel"),  // KC_CRSEL
        0x00A4: QMKKeycodeLabel(tap: "Exsel"),  // KC_EXSEL
        0x00A5: QMKKeycodeLabel(tap: "Pwr"),  // KC_PWR
        0x00A6: QMKKeycodeLabel(tap: "Slep"),  // KC_SLEP
        0x00A7: QMKKeycodeLabel(tap: "Wake"),  // KC_WAKE
        0x00A8: QMKKeycodeLabel(tap: "Mute"),  // KC_MUTE
        0x00A9: QMKKeycodeLabel(tap: "Vol+"),  // KC_VOLU
        0x00AA: QMKKeycodeLabel(tap: "Vol-"),  // KC_VOLD
        0x00AB: QMKKeycodeLabel(tap: "Next"),  // KC_MNXT
        0x00AC: QMKKeycodeLabel(tap: "Prev"),  // KC_MPRV
        0x00AD: QMKKeycodeLabel(tap: "Stop"),  // KC_MSTP
        0x00AE: QMKKeycodeLabel(tap: "Play"),  // KC_MPLY
        0x00AF: QMKKeycodeLabel(tap: "Media"),  // KC_MSEL
        0x00B0: QMKKeycodeLabel(tap: "Eject"),  // KC_EJCT
        0x00B1: QMKKeycodeLabel(tap: "Mail"),  // KC_MAIL
        0x00B2: QMKKeycodeLabel(tap: "Calc"),  // KC_CALC
        0x00B3: QMKKeycodeLabel(tap: "PC"),  // KC_MYCM
        0x00B4: QMKKeycodeLabel(tap: "Search"),  // KC_WWW_SEARCH
        0x00B5: QMKKeycodeLabel(tap: "Home"),  // KC_WWW_HOME
        0x00B6: QMKKeycodeLabel(tap: "Back"),  // KC_WWW_BACK
        0x00B7: QMKKeycodeLabel(tap: "Fwd"),  // KC_WWW_FORWARD
        0x00B8: QMKKeycodeLabel(tap: "Stop"),  // KC_WWW_STOP
        0x00B9: QMKKeycodeLabel(tap: "Refresh"),  // KC_WWW_REFRESH
        0x00BA: QMKKeycodeLabel(tap: "Favs"),  // KC_WWW_FAVORITES
        0x00BB: QMKKeycodeLabel(tap: "FF"),  // KC_MFFD
        0x00BC: QMKKeycodeLabel(tap: "Rew"),  // KC_MRWD
        0x00BD: QMKKeycodeLabel(tap: "Bright+"),  // KC_BRIU
        0x00BE: QMKKeycodeLabel(tap: "Bright-"),  // KC_BRID
        0x00CD: QMKKeycodeLabel(tap: "Ms Up"),  // KC_MS_UP
        0x00CE: QMKKeycodeLabel(tap: "Ms Down"),  // KC_MS_DOWN
        0x00CF: QMKKeycodeLabel(tap: "Ms Left"),  // KC_MS_LEFT
        0x00D0: QMKKeycodeLabel(tap: "Ms Right"),  // KC_MS_RIGHT
        0x00D1: QMKKeycodeLabel(tap: "Ms Btn1"),  // KC_MS_BTN1
        0x00D2: QMKKeycodeLabel(tap: "Ms Btn2"),  // KC_MS_BTN2
        0x00D3: QMKKeycodeLabel(tap: "Ms Btn3"),  // KC_MS_BTN3
        0x00D4: QMKKeycodeLabel(tap: "Ms Btn4"),  // KC_MS_BTN4
        0x00D5: QMKKeycodeLabel(tap: "Ms Btn5"),  // KC_MS_BTN5
        0x00D6: QMKKeycodeLabel(tap: "Ms Btn6"),  // KC_MS_BTN6
        0x00D7: QMKKeycodeLabel(tap: "Ms Btn7"),  // KC_MS_BTN7
        0x00D8: QMKKeycodeLabel(tap: "Ms Btn8"),  // KC_MS_BTN8
        0x00D9: QMKKeycodeLabel(tap: "Ms Wh Up"),  // KC_MS_WH_UP
        0x00DA: QMKKeycodeLabel(tap: "Ms Wh Down"),  // KC_MS_WH_DOWN
        0x00DB: QMKKeycodeLabel(tap: "Ms Wh Left"),  // KC_MS_WH_LEFT
        0x00DC: QMKKeycodeLabel(tap: "Ms Wh Right"),  // KC_MS_WH_RIGHT
        0x00DD: QMKKeycodeLabel(tap: "Ms Accel0"),  // KC_MS_ACCEL0
        0x00DE: QMKKeycodeLabel(tap: "Ms Accel1"),  // KC_MS_ACCEL1
        0x00DF: QMKKeycodeLabel(tap: "Ms Accel2"),  // KC_MS_ACCEL2
        0x00E0: QMKKeycodeLabel(tap: "LCtrl"),  // KC_LCTL
        0x00E1: QMKKeycodeLabel(tap: "LShift"),  // KC_LSFT
        0x00E2: QMKKeycodeLabel(tap: "LAlt"),  // KC_LALT
        0x00E3: QMKKeycodeLabel(tap: "LCmd"),  // KC_LGUI
        0x00E4: QMKKeycodeLabel(tap: "RCtrl"),  // KC_RCTL
        0x00E5: QMKKeycodeLabel(tap: "RShift"),  // KC_RSFT
        0x00E6: QMKKeycodeLabel(tap: "RAlt"),  // KC_RALT
        0x00E7: QMKKeycodeLabel(tap: "RCmd"),  // KC_RGUI
        0x7013: QMKKeycodeLabel(tap: "NKRO"),  // MAGIC_TOGGLE_NKRO
        0x7017: QMKKeycodeLabel(tap: "Swap Lctl Lgui"),  // MAGIC_SWAP_LCTL_LGUI
        0x7018: QMKKeycodeLabel(tap: "Unswap Lctl Lgui"),  // MAGIC_UNSWAP_LCTL_LGUI
        0x7019: QMKKeycodeLabel(tap: "Swap Rctl Rgui"),  // MAGIC_SWAP_RCTL_RGUI
        0x701A: QMKKeycodeLabel(tap: "Unswap Rctl Rgui"),  // MAGIC_UNSWAP_RCTL_RGUI
        0x701B: QMKKeycodeLabel(tap: "Swap Ctl Gui"),  // MAGIC_SWAP_CTL_GUI
        0x701C: QMKKeycodeLabel(tap: "Unswap Ctl Gui"),  // MAGIC_UNSWAP_CTL_GUI
        0x701D: QMKKeycodeLabel(tap: "Toggle Ctl Gui"),  // MAGIC_TOGGLE_CTL_GUI
        0x701E: QMKKeycodeLabel(tap: "Ee Hands Left"),  // MAGIC_EE_HANDS_LEFT
        0x701F: QMKKeycodeLabel(tap: "Ee Hands Right"),  // MAGIC_EE_HANDS_RIGHT
        0x7100: QMKKeycodeLabel(tap: "Mi On"),  // MI_ON
        0x7101: QMKKeycodeLabel(tap: "Mi Off"),  // MI_OFF
        0x7102: QMKKeycodeLabel(tap: "Mi Tog"),  // MI_TOG
        0x7110: QMKKeycodeLabel(tap: "Mi C"),  // MI_C
        0x7112: QMKKeycodeLabel(tap: "Mi D"),  // MI_D
        0x7114: QMKKeycodeLabel(tap: "Mi E"),  // MI_E
        0x7115: QMKKeycodeLabel(tap: "Mi F"),  // MI_F
        0x7117: QMKKeycodeLabel(tap: "Mi G"),  // MI_G
        0x7119: QMKKeycodeLabel(tap: "Mi A"),  // MI_A
        0x711B: QMKKeycodeLabel(tap: "Mi B"),  // MI_B
        0x7120: QMKKeycodeLabel(tap: "Mi C 1"),  // MI_C_1
        0x7122: QMKKeycodeLabel(tap: "Mi D 1"),  // MI_D_1
        0x7124: QMKKeycodeLabel(tap: "Mi E 1"),  // MI_E_1
        0x7125: QMKKeycodeLabel(tap: "Mi F 1"),  // MI_F_1
        0x7127: QMKKeycodeLabel(tap: "Mi G 1"),  // MI_G_1
        0x7129: QMKKeycodeLabel(tap: "Mi A 1"),  // MI_A_1
        0x712B: QMKKeycodeLabel(tap: "Mi B 1"),  // MI_B_1
        0x7130: QMKKeycodeLabel(tap: "Mi C 2"),  // MI_C_2
        0x7132: QMKKeycodeLabel(tap: "Mi D 2"),  // MI_D_2
        0x7134: QMKKeycodeLabel(tap: "Mi E 2"),  // MI_E_2
        0x7135: QMKKeycodeLabel(tap: "Mi F 2"),  // MI_F_2
        0x7137: QMKKeycodeLabel(tap: "Mi G 2"),  // MI_G_2
        0x7139: QMKKeycodeLabel(tap: "Mi A 2"),  // MI_A_2
        0x713B: QMKKeycodeLabel(tap: "Mi B 2"),  // MI_B_2
        0x7140: QMKKeycodeLabel(tap: "Mi C 3"),  // MI_C_3
        0x7142: QMKKeycodeLabel(tap: "Mi D 3"),  // MI_D_3
        0x7144: QMKKeycodeLabel(tap: "Mi E 3"),  // MI_E_3
        0x7145: QMKKeycodeLabel(tap: "Mi F 3"),  // MI_F_3
        0x7147: QMKKeycodeLabel(tap: "Mi G 3"),  // MI_G_3
        0x7149: QMKKeycodeLabel(tap: "Mi A 3"),  // MI_A_3
        0x714B: QMKKeycodeLabel(tap: "Mi B 3"),  // MI_B_3
        0x7150: QMKKeycodeLabel(tap: "Mi C 4"),  // MI_C_4
        0x7152: QMKKeycodeLabel(tap: "Mi D 4"),  // MI_D_4
        0x7154: QMKKeycodeLabel(tap: "Mi E 4"),  // MI_E_4
        0x7155: QMKKeycodeLabel(tap: "Mi F 4"),  // MI_F_4
        0x7157: QMKKeycodeLabel(tap: "Mi G 4"),  // MI_G_4
        0x7159: QMKKeycodeLabel(tap: "Mi A 4"),  // MI_A_4
        0x715B: QMKKeycodeLabel(tap: "Mi B 4"),  // MI_B_4
        0x7160: QMKKeycodeLabel(tap: "Mi C 5"),  // MI_C_5
        0x7162: QMKKeycodeLabel(tap: "Mi D 5"),  // MI_D_5
        0x7164: QMKKeycodeLabel(tap: "Mi E 5"),  // MI_E_5
        0x7165: QMKKeycodeLabel(tap: "Mi F 5"),  // MI_F_5
        0x7167: QMKKeycodeLabel(tap: "Mi G 5"),  // MI_G_5
        0x7169: QMKKeycodeLabel(tap: "Mi A 5"),  // MI_A_5
        0x716B: QMKKeycodeLabel(tap: "Mi B 5"),  // MI_B_5
        0x7170: QMKKeycodeLabel(tap: "Mi Oct N2"),  // MI_OCT_N2
        0x7171: QMKKeycodeLabel(tap: "Mi Oct N1"),  // MI_OCT_N1
        0x7172: QMKKeycodeLabel(tap: "Mi Oct 0"),  // MI_OCT_0
        0x7173: QMKKeycodeLabel(tap: "Mi Oct 1"),  // MI_OCT_1
        0x7174: QMKKeycodeLabel(tap: "Mi Oct 2"),  // MI_OCT_2
        0x7175: QMKKeycodeLabel(tap: "Mi Oct 3"),  // MI_OCT_3
        0x7176: QMKKeycodeLabel(tap: "Mi Oct 4"),  // MI_OCT_4
        0x7177: QMKKeycodeLabel(tap: "Mi Oct 5"),  // MI_OCT_5
        0x7178: QMKKeycodeLabel(tap: "Mi Oct 6"),  // MI_OCT_6
        0x7179: QMKKeycodeLabel(tap: "Mi Oct 7"),  // MI_OCT_7
        0x717A: QMKKeycodeLabel(tap: "Mi Octd"),  // MI_OCTD
        0x717B: QMKKeycodeLabel(tap: "Mi Octu"),  // MI_OCTU
        0x7180: QMKKeycodeLabel(tap: "Mi Trns N6"),  // MI_TRNS_N6
        0x7181: QMKKeycodeLabel(tap: "Mi Trns N5"),  // MI_TRNS_N5
        0x7182: QMKKeycodeLabel(tap: "Mi Trns N4"),  // MI_TRNS_N4
        0x7183: QMKKeycodeLabel(tap: "Mi Trns N3"),  // MI_TRNS_N3
        0x7184: QMKKeycodeLabel(tap: "Mi Trns N2"),  // MI_TRNS_N2
        0x7185: QMKKeycodeLabel(tap: "Mi Trns N1"),  // MI_TRNS_N1
        0x7186: QMKKeycodeLabel(tap: "Mi Trns 0"),  // MI_TRNS_0
        0x7187: QMKKeycodeLabel(tap: "Mi Trns 1"),  // MI_TRNS_1
        0x7188: QMKKeycodeLabel(tap: "Mi Trns 2"),  // MI_TRNS_2
        0x7189: QMKKeycodeLabel(tap: "Mi Trns 3"),  // MI_TRNS_3
        0x718A: QMKKeycodeLabel(tap: "Mi Trns 4"),  // MI_TRNS_4
        0x718B: QMKKeycodeLabel(tap: "Mi Trns 5"),  // MI_TRNS_5
        0x718C: QMKKeycodeLabel(tap: "Mi Trns 6"),  // MI_TRNS_6
        0x718D: QMKKeycodeLabel(tap: "Mi Trnsd"),  // MI_TRNSD
        0x718E: QMKKeycodeLabel(tap: "Mi Trnsu"),  // MI_TRNSU
        0x7190: QMKKeycodeLabel(tap: "Mi Vel 0"),  // MI_VEL_0
        0x7191: QMKKeycodeLabel(tap: "Mi Vel 1"),  // MI_VEL_1
        0x7192: QMKKeycodeLabel(tap: "Mi Vel 2"),  // MI_VEL_2
        0x7193: QMKKeycodeLabel(tap: "Mi Vel 3"),  // MI_VEL_3
        0x7194: QMKKeycodeLabel(tap: "Mi Vel 4"),  // MI_VEL_4
        0x7195: QMKKeycodeLabel(tap: "Mi Vel 5"),  // MI_VEL_5
        0x7196: QMKKeycodeLabel(tap: "Mi Vel 6"),  // MI_VEL_6
        0x7197: QMKKeycodeLabel(tap: "Mi Vel 7"),  // MI_VEL_7
        0x7198: QMKKeycodeLabel(tap: "Mi Vel 8"),  // MI_VEL_8
        0x7199: QMKKeycodeLabel(tap: "Mi Vel 9"),  // MI_VEL_9
        0x719A: QMKKeycodeLabel(tap: "Mi Vel 10"),  // MI_VEL_10
        0x719B: QMKKeycodeLabel(tap: "Mi Veld"),  // MI_VELD
        0x719C: QMKKeycodeLabel(tap: "Mi Velu"),  // MI_VELU
        0x71A0: QMKKeycodeLabel(tap: "Mi Ch1"),  // MI_CH1
        0x71A1: QMKKeycodeLabel(tap: "Mi Ch2"),  // MI_CH2
        0x71A2: QMKKeycodeLabel(tap: "Mi Ch3"),  // MI_CH3
        0x71A3: QMKKeycodeLabel(tap: "Mi Ch4"),  // MI_CH4
        0x71A4: QMKKeycodeLabel(tap: "Mi Ch5"),  // MI_CH5
        0x71A5: QMKKeycodeLabel(tap: "Mi Ch6"),  // MI_CH6
        0x71A6: QMKKeycodeLabel(tap: "Mi Ch7"),  // MI_CH7
        0x71A7: QMKKeycodeLabel(tap: "Mi Ch8"),  // MI_CH8
        0x71A8: QMKKeycodeLabel(tap: "Mi Ch9"),  // MI_CH9
        0x71A9: QMKKeycodeLabel(tap: "Mi Ch10"),  // MI_CH10
        0x71AA: QMKKeycodeLabel(tap: "Mi Ch11"),  // MI_CH11
        0x71AB: QMKKeycodeLabel(tap: "Mi Ch12"),  // MI_CH12
        0x71AC: QMKKeycodeLabel(tap: "Mi Ch13"),  // MI_CH13
        0x71AD: QMKKeycodeLabel(tap: "Mi Ch14"),  // MI_CH14
        0x71AE: QMKKeycodeLabel(tap: "Mi Ch15"),  // MI_CH15
        0x71AF: QMKKeycodeLabel(tap: "Mi Ch16"),  // MI_CH16
        0x71B0: QMKKeycodeLabel(tap: "Mi Chd"),  // MI_CHD
        0x71B1: QMKKeycodeLabel(tap: "Mi Chu"),  // MI_CHU
        0x71C0: QMKKeycodeLabel(tap: "Mi Alloff"),  // MI_ALLOFF
        0x71C1: QMKKeycodeLabel(tap: "Mi Sust"),  // MI_SUST
        0x71C2: QMKKeycodeLabel(tap: "Mi Port"),  // MI_PORT
        0x71C3: QMKKeycodeLabel(tap: "Mi Sost"),  // MI_SOST
        0x71C4: QMKKeycodeLabel(tap: "Mi Soft"),  // MI_SOFT
        0x71C5: QMKKeycodeLabel(tap: "Mi Leg"),  // MI_LEG
        0x71C6: QMKKeycodeLabel(tap: "Mi Mod"),  // MI_MOD
        0x71C7: QMKKeycodeLabel(tap: "Mi Modsd"),  // MI_MODSD
        0x71C8: QMKKeycodeLabel(tap: "Mi Modsu"),  // MI_MODSU
        0x71C9: QMKKeycodeLabel(tap: "Mi Bendd"),  // MI_BENDD
        0x71CA: QMKKeycodeLabel(tap: "Mi Bendu"),  // MI_BENDU
        0x7480: QMKKeycodeLabel(tap: "Au On"),  // AU_ON
        0x7481: QMKKeycodeLabel(tap: "Au Off"),  // AU_OFF
        0x7482: QMKKeycodeLabel(tap: "Au Tog"),  // AU_TOG
        0x748A: QMKKeycodeLabel(tap: "Clicky Toggle"),  // CLICKY_TOGGLE
        0x748B: QMKKeycodeLabel(tap: "Clicky Enable"),  // CLICKY_ENABLE
        0x748C: QMKKeycodeLabel(tap: "Clicky Disable"),  // CLICKY_DISABLE
        0x748D: QMKKeycodeLabel(tap: "Clicky Up"),  // CLICKY_UP
        0x748E: QMKKeycodeLabel(tap: "Clicky Down"),  // CLICKY_DOWN
        0x748F: QMKKeycodeLabel(tap: "Clicky Reset"),  // CLICKY_RESET
        0x7490: QMKKeycodeLabel(tap: "Music On"),  // MU_ON
        0x7491: QMKKeycodeLabel(tap: "Music Off"),  // MU_OFF
        0x7492: QMKKeycodeLabel(tap: "Music"),  // MU_TOG
        0x7493: QMKKeycodeLabel(tap: "Music Mode"),  // MU_MOD
        0x7800: QMKKeycodeLabel(tap: "BL On"),  // BL_ON
        0x7801: QMKKeycodeLabel(tap: "BL Off"),  // BL_OFF
        0x7802: QMKKeycodeLabel(tap: "BL"),  // BL_TOGG
        0x7803: QMKKeycodeLabel(tap: "BL-"),  // BL_DEC
        0x7804: QMKKeycodeLabel(tap: "BL+"),  // BL_INC
        0x7805: QMKKeycodeLabel(tap: "BL Step"),  // BL_STEP
        0x7806: QMKKeycodeLabel(tap: "BL Breathe"),  // BL_BRTG
        0x7820: QMKKeycodeLabel(tap: "RGB"),  // RGB_TOG
        0x7821: QMKKeycodeLabel(tap: "RGB+"),  // RGB_MOD
        0x7822: QMKKeycodeLabel(tap: "RGB-"),  // RGB_RMOD
        0x7823: QMKKeycodeLabel(tap: "Hue+"),  // RGB_HUI
        0x7824: QMKKeycodeLabel(tap: "Hue-"),  // RGB_HUD
        0x7825: QMKKeycodeLabel(tap: "Sat+"),  // RGB_SAI
        0x7826: QMKKeycodeLabel(tap: "Sat-"),  // RGB_SAD
        0x7827: QMKKeycodeLabel(tap: "Val+"),  // RGB_VAI
        0x7828: QMKKeycodeLabel(tap: "Val-"),  // RGB_VAD
        0x7829: QMKKeycodeLabel(tap: "Speed+"),  // RGB_SPI
        0x782A: QMKKeycodeLabel(tap: "Speed-"),  // RGB_SPD
        0x782B: QMKKeycodeLabel(tap: "RGB Plain"),  // RGB_M_P
        0x782C: QMKKeycodeLabel(tap: "RGB Breathe"),  // RGB_M_B
        0x782D: QMKKeycodeLabel(tap: "RGB Rainbow"),  // RGB_M_R
        0x782E: QMKKeycodeLabel(tap: "RGB Swirl"),  // RGB_M_SW
        0x782F: QMKKeycodeLabel(tap: "RGB Snake"),  // RGB_M_SN
        0x7830: QMKKeycodeLabel(tap: "RGB Knight"),  // RGB_M_K
        0x7831: QMKKeycodeLabel(tap: "RGB Xmas"),  // RGB_M_X
        0x7832: QMKKeycodeLabel(tap: "RGB Gradient"),  // RGB_M_G
        0x7833: QMKKeycodeLabel(tap: "Mode Rgbtest"),  // RGB_MODE_RGBTEST
        0x7C00: QMKKeycodeLabel(tap: "Reset"),  // RESET
        0x7C02: QMKKeycodeLabel(tap: "Debug"),  // DEBUG
        0x7C03: QMKKeycodeLabel(tap: "Clear Eeprom"),  // QK_CLEAR_EEPROM
        0x7C10: QMKKeycodeLabel(tap: "Asdn"),  // KC_ASDN
        0x7C11: QMKKeycodeLabel(tap: "Asup"),  // KC_ASUP
        0x7C12: QMKKeycodeLabel(tap: "Asrp"),  // KC_ASRP
        0x7C13: QMKKeycodeLabel(tap: "Ason"),  // KC_ASON
        0x7C14: QMKKeycodeLabel(tap: "Asoff"),  // KC_ASOFF
        0x7C15: QMKKeycodeLabel(tap: "Astg"),  // KC_ASTG
        0x7C16: QMKKeycodeLabel(tap: "GEsc"),  // KC_GESC
        0x7C17: QMKKeycodeLabel(tap: "Vlk Tog"),  // VLK_TOG
        0x7C18: QMKKeycodeLabel(tap: "Lcpo"),  // KC_LCPO
        0x7C19: QMKKeycodeLabel(tap: "Rcpc"),  // KC_RCPC
        0x7C1A: QMKKeycodeLabel(tap: "Lspo"),  // KC_LSPO
        0x7C1B: QMKKeycodeLabel(tap: "Rspc"),  // KC_RSPC
        0x7C1C: QMKKeycodeLabel(tap: "Lapo"),  // KC_LAPO
        0x7C1D: QMKKeycodeLabel(tap: "Rapc"),  // KC_RAPC
        0x7C1E: QMKKeycodeLabel(tap: "Sftent"),  // KC_SFTENT
        0x7C20: QMKKeycodeLabel(tap: "Out Auto"),  // OUT_AUTO
        0x7C21: QMKKeycodeLabel(tap: "Out Usb"),  // OUT_USB
        0x7C40: QMKKeycodeLabel(tap: "Hpt On"),  // HPT_ON
        0x7C41: QMKKeycodeLabel(tap: "Hpt Off"),  // HPT_OFF
        0x7C42: QMKKeycodeLabel(tap: "Hpt Tog"),  // HPT_TOG
        0x7C43: QMKKeycodeLabel(tap: "Hpt Rst"),  // HPT_RST
        0x7C44: QMKKeycodeLabel(tap: "Hpt Fbk"),  // HPT_FBK
        0x7C45: QMKKeycodeLabel(tap: "Hpt Buz"),  // HPT_BUZ
        0x7C46: QMKKeycodeLabel(tap: "Hpt Modi"),  // HPT_MODI
        0x7C47: QMKKeycodeLabel(tap: "Hpt Modd"),  // HPT_MODD
        0x7C48: QMKKeycodeLabel(tap: "Hpt Cont"),  // HPT_CONT
        0x7C49: QMKKeycodeLabel(tap: "Hpt Coni"),  // HPT_CONI
        0x7C4A: QMKKeycodeLabel(tap: "Hpt Cond"),  // HPT_COND
        0x7C4B: QMKKeycodeLabel(tap: "Hpt Dwli"),  // HPT_DWLI
        0x7C4C: QMKKeycodeLabel(tap: "Hpt Dwld"),  // HPT_DWLD
        0x7C50: QMKKeycodeLabel(tap: "Cmb On"),  // CMB_ON
        0x7C51: QMKKeycodeLabel(tap: "Cmb Off"),  // CMB_OFF
        0x7C52: QMKKeycodeLabel(tap: "Cmb Tog"),  // CMB_TOG
        0x7C53: QMKKeycodeLabel(tap: "Dyn Rec Start1"),  // DYN_REC_START1
        0x7C54: QMKKeycodeLabel(tap: "Dyn Rec Start2"),  // DYN_REC_START2
        0x7C55: QMKKeycodeLabel(tap: "Dyn Rec Stop"),  // DYN_REC_STOP
        0x7C56: QMKKeycodeLabel(tap: "Dyn Macro Play1"),  // DYN_MACRO_PLAY1
        0x7C57: QMKKeycodeLabel(tap: "Dyn Macro Play2"),  // DYN_MACRO_PLAY2
        0x7C77: QMKKeycodeLabel(tap: "Fn Mo13"),  // FN_MO13
        0x7C78: QMKKeycodeLabel(tap: "Fn Mo23"),  // FN_MO23
    ]
}

extension VIAKeycodeMap {
    static let v10Ranges: VIAKeycodeRanges = VIAKeycodeRanges(
        mods: 0x0100 ..< 0x2000,
        modTap: 0x6000 ..< 0x8000,
        layerTap: 0x4000 ..< 0x5000,
        layerMod: 0x5900 ..< 0x5A00,
        toLayer: 0x5000 ..< 0x5020,
        momentary: 0x5100 ..< 0x5120,
        defaultLayer: 0x5200 ..< 0x5220,
        toggleLayer: 0x5300 ..< 0x5320,
        oneShotLayer: 0x5400 ..< 0x5420,
        oneShotMod: 0x5500 ..< 0x5600,
        layerTapToggle: 0x5800 ..< 0x5820,
        macro: 0x5F12 ..< 0x5F22,
        kbCustom: 0x5F80 ..< 0x5F90
    )
}

extension VIAKeycodeMap {
    static let v11Ranges: VIAKeycodeRanges = VIAKeycodeRanges(
        mods: 0x0100 ..< 0x2000,
        modTap: 0x2000 ..< 0x4000,
        layerTap: 0x4000 ..< 0x5000,
        layerMod: 0x5000 ..< 0x5200,
        toLayer: 0x5200 ..< 0x5220,
        momentary: 0x5220 ..< 0x5240,
        defaultLayer: 0x5240 ..< 0x5260,
        toggleLayer: 0x5260 ..< 0x5280,
        oneShotLayer: 0x5280 ..< 0x52A0,
        oneShotMod: 0x52A0 ..< 0x52C0,
        layerTapToggle: 0x52C0 ..< 0x52E0,
        macro: 0x7702 ..< 0x7712,
        kbCustom: 0x7F00 ..< 0x8000
    )
}

extension VIAKeycodeMap {
    static let v12Ranges: VIAKeycodeRanges = VIAKeycodeRanges(
        mods: 0x0100 ..< 0x2000,
        modTap: 0x2000 ..< 0x4000,
        layerTap: 0x4000 ..< 0x5000,
        layerMod: 0x5000 ..< 0x5200,
        toLayer: 0x5200 ..< 0x5220,
        momentary: 0x5220 ..< 0x5240,
        defaultLayer: 0x5240 ..< 0x5260,
        toggleLayer: 0x5260 ..< 0x5280,
        oneShotLayer: 0x5280 ..< 0x52A0,
        oneShotMod: 0x52A0 ..< 0x52C0,
        layerTapToggle: 0x52C0 ..< 0x52E0,
        macro: 0x7700 ..< 0x7780,
        kbCustom: 0x7E00 ..< 0x7F00
    )
}
